### ISSUE TITLE
<li> bulletpoint / numeral not being styled along with content of <li>

### ISSUE THREAD

**Issue by f6m6** [meliorence/react-native-render-html#144]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

In the Demo, changing `lists: { name: 'Lists', props: { baseFontSize: 14 } }` to `lists: { name: 'Lists', props: { baseFontSize: 2 } }` and it had no effect on the font size so I couldn't reproduce it, but that's a problem in itself.

### Environment
    React: 16.2.0
    React native: 0.52.0
    react-native-render-html: 3.9.1

  Target Platform:
    Android (6.0)
    iOS (11.2)

### Steps to Reproduce
1. Go to the Demo app in this repo
2. Go to the file snippets.js
3. Change `lists: { name: 'Lists', props: { baseFontSize: 14 } }` to `lists: { name: 'Lists', props: { baseFontSize: 2 } }`

### Expected Behavior

<li> text and bullets should be resizable. Changing baseFontSize to 2 should have made it very small.

### Actual Behavior

<li> tags cannot be resized

### Reproducible Demo

One step only:

In the Demo, changing `lists: { name: 'Lists', props: { baseFontSize: 14 } }` to `lists: { name: 'Lists', props: { baseFontSize: 2 } }` and it had no effect on the font size so I couldn't reproduce it, but that's a problem in itself.

<img width="295" alt="screen shot 2018-05-03 at 17 59 45" src="https://user-images.githubusercontent.com/603598/39591527-e87f9ab4-4efb-11e8-8a06-5c2280a38aff.png">

**Comment by farhanmannan** [comment]
This is part of a wider problem I have as in my real project, my `<li>` text does grow larger - seems to take on the `p` tag's style even though that is not in my html - but the bullets do not, causing misalignment which I need to correct.

![screen shot 2018-05-03 at 17 27 25](https://user-images.githubusercontent.com/603598/39591579-1725ff0c-4efc-11e8-8c1a-0635ee8a2a7b.png)
<img width="295" alt="screen shot 2018-05-03 at 17 19 22" src="https://user-images.githubusercontent.com/603598/39591580-173ef872-4efc-11e8-98d7-f43befcf6bbe.png">

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).
