### ISSUE TITLE
Warning when passing tagStyles to p, h1, h2, h3, etc. wrapping an img tag

### ISSUE THREAD

**Issue by wpalahnuk** [meliorence/react-native-render-html#150]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android 8.0 (API level 26)
Unsure about iOS

### Is the bug reproductible in a production environment (not a debug one)?

Unsure

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes, in this file: https://github.com/archriss/react-native-render-html/blob/master/Demo/src/snippets.js

Change:

`imagesWithinParagraphs: { name: 'Images within paragraphs' },`

To this:

```
imagesWithinParagraphs: { name: 'Images within paragraphs', 
    props: { 
        tagsStyles: {
            p: { fontSize: 10 }
        }
    } 
},
```
You will see the error: Warning: Failed prop type: Invalid props.style key `fontSize` supplied to `View`.

I find similar issues with img tags wrapped in h1, h2, h3, etc. tags

### Environment

  Environment:
    React: 16.3.1
    React native: 0.55.0
    react-native-render-html: 3.10.0

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Steps to Reproduce

In this file: https://github.com/archriss/react-native-render-html/blob/master/Demo/src/snippets.js

Change:

`imagesWithinParagraphs: { name: 'Images within paragraphs' },`

To this:

```
imagesWithinParagraphs: { name: 'Images within paragraphs', 
    props: { 
        tagsStyles: {
            p: { fontSize: 10 }
        }
    } 
},
```

### Expected Behavior

No warning

### Actual Behavior

A warning is being shown: 
Warning: Failed prop type: Invalid props.style key `fontSize` supplied to `View`.

### Reproducible Demo

In this file: https://github.com/archriss/react-native-render-html/blob/master/Demo/src/snippets.js

Change:

`imagesWithinParagraphs: { name: 'Images within paragraphs' },`

To this:

```
imagesWithinParagraphs: { name: 'Images within paragraphs', 
    props: { 
        tagsStyles: {
            p: { fontSize: 10 }
        }
    } 
},
```

**Comment by Exilz** [comment]
This is due to the most recent code which handles styles inheritance in text elements. There should be a logic which prevents non-text styling to be passed down all the way to texts.

If anyone wants to look into this, I'll gladly review a pull request. Anyway, this shouldn't be a breaking bug.

**Comment by jsamr** [comment]
This is fixed in the Foundry release, you can try it out now! See #434.

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).
