### ISSUE TITLE
Bullet points not changing color with tagStyles for ul / li

### ISSUE THREAD

**Issue by JungleCatSW** [meliorence/react-native-render-html#151]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?
Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
Both
(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)
iPhone 5, iPhone 6, Galaxy Tab 3, Galaxy S8, Nexus 5, Galaxy A3
### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

  Environment:
    React: 16.0.0
    React native: 0.52
    react-native-render-html: 3.10.0

  Target Platform:
    Android 8.1 / 27
    iOS 11

### Steps to Reproduce

When using custom tagStyles to color bulleted lists the bullet image doesn't change color but the text does.

Please see snack
[`Snack of issue`](https://snack.expo.io/SktdrQhCz)

### Expected Behavior

I though the bullet point images would be the same color as the text.

### Actual Behavior

The bullet points stayed black.

![screenshot_20180518-111347_expo](https://user-images.githubusercontent.com/14792977/40229685-e3568ae2-5a8c-11e8-912d-3cb0373a3eff.jpg)

### Reproducible Demo

# Please see snack
[`Snack of issue`](https://snack.expo.io/SktdrQhCz)

**Comment by JungleCatSW** [comment]
Also I'm fairly sure its line 91 of this file https://github.com/archriss/react-native-render-html/blob/master/src/HTMLRenderers.js that needs to take the color style from props ?

**Comment by donni106** [comment]
@JungleCatSW do you made it?
I think you need a special `listsPrefixesRenderers` to color the bullets or numbers. See https://github.com/archriss/react-native-render-html/issues/165#issuecomment-411811568 how to do it.

**Comment by jsamr** [comment]
<table>
<tr>
<td valign="top">

This issue has been fixed in the Foundry release. Try it out now! See #430 for instructions.

</td>
<td width="300">
<img width="300" src="https://user-images.githubusercontent.com/3646758/100381340-90574c80-2ff7-11eb-8289-2a435a2e0798.png" />
</td>
</tr>
</table>

**Comment by dzpt** [comment]
@jsamr any chance to fix it on v5? v6 tends to be unstable and lot of issue?
