### ISSUE TITLE
Empty line in output, even if there is no <br> or other Tag to parse

### ISSUE THREAD

**Issue by xstable** [meliorence/react-native-render-html#156]
I have this HTML:
```json
{"intro": "<p>Damit der Veranstaltungsbesuch ein schönes Erlebnis mit bleibender Erinnerung wird, bitten wir alle Festivalbesucher um die Beachtung der nachfolgenden Hinweise.<br></p><p>Informationen für Konzertbesucher und Antworten auf oft gestellte Fragen finden Sie hier: <a href=\"/besucherservice#faq\">FAQ</a></p><p>Bitte beachten Sie unsere: <a href=\"/besucherservice#sicherheitshinweise\">Sicherheitshinweise</a></p>"
}
```
This creates an additional empty line in the App: 
![auswahl_761](https://user-images.githubusercontent.com/1778068/40483230-8ceb1054-5f57-11e8-9edc-dd4e88e4b61d.jpg)

Here is my JSX: 

```JS
 {(data.text !== undefined && data.text !== "") ?
                <Row >
                    <HTML style={styles.detailText}
                          html={data.text}
                          debug={false}
                          onLinkPress={(event, href) => {
                              //TODO: If internal link, use Navigate, instead of Linking ... to link in App instead of Browser.
                              Linking.openURL(ParseUrl(href)).catch(e => console.log("Fehler beim Aufruf der url: " + href, e));
                          }}
                          baseFontStyle={fontStyles}
                          tagsStyles={tagStyles}
                          imagesMaxWidth={Dimensions.get('window').width}
                    />
                </Row > : null
            }
```

It seems only to happen, if there is an  \<a href\> as last element in front of the closing \</p\>-Tag.

**Comment by AishwaryaSurana** [comment]
Is this bug fixed? @Exilz
@xstable How are you able to fix it?

**Comment by egealpay** [comment]
Is it solved?

**Comment by jsamr** [comment]
This issue has been solved in the Foundry release! You can try it out now. See #434. Below is a screenshot with the provided snippet

![Screenshot_1606406920](https://user-images.githubusercontent.com/3646758/100372863-a4478200-2fe8-11eb-9598-32d2c8c113b5.png)

**Comment by jsamr** [comment]
This issue has been fixed in the Foundry release. Try it out now! See #430 for instructions.

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).
