### ISSUE TITLE
Find children of a node recursively

### ISSUE THREAD

**Issue by rok5ek** [meliorence/react-native-render-html#160]
### Is this a bug report or a feature request?

Feature request

Currently i have an "img" that is wrapped inside a "p" `<p><img/></p>` and I'm setting a margin to all of the tags except to the "img" tag since i want it to be fullscreen width. I'm doing this with alterNode method where I add the margin style to all of the tags except the "img" tag, but the problem is that the "img" tag is wrapped inside the "p" tag.

Is there a way to check if a tag contains any children with specific tag?
I saw a method "getParentsTagsRecursively" but that only returns parents of a tag.

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

It's not a bug.

### Is the bug reproductible in a production environment (not a debug one)?

It's not a bug.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

  Environment:
    React: 16.0.0-beta.5
    React native: 0.49.2
    react-native-render-html: 3.9.0

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Steps to Reproduce

It's not a bug.

(Write your steps here:)

It's not a bug.

### Expected Behavior

It's not a bug.

### Actual Behavior

It's not a bug.

**Comment by jsamr** [comment]
@rok5ek This library uses `htmlparser2` to create a DOM. `htmlparser2` has utility libraries to do just that (see [domutils](https://github.com/fb55/domutils)). Especially, check the [querying functions](https://github.com/fb55/domutils/blob/master/src/querying.ts), `find`, `findOne`, `findOneChild`, `findAll` ...
