### ISSUE TITLE
Passing a baseurl as a prop

### ISSUE THREAD

**Issue by Nicholson85** [meliorence/react-native-render-html#227]
### Is this a bug report or a feature request?

Feature Request

Apologies if this comes across is a dumb question but I was just wondering.  Is it possible to provide a 'baseurl' as a prop similar to a webview which would then be prepended to any relative paths in the html.  I am aware this could be done by using custom renderers but was unsure if there was a simpler way.

Thanks.

**Comment by Exilz** [comment]
We could add it as a prop in the future. It would need to affect all the default renderers and be available in the parameters of the custom renderers, though.
This shouldn't be too complicated but there are quite a lot of code changes to make. I don't plan on making it myself in the near future, but I'm open to reviewing a pull request and merging it.

I'm not sure this is a feature needed by many, so I wouldn't make that a priority. 😄

**Comment by jsamr** [comment]
This feature is available in the foundry pre-release (see #430 for instruction on how to try it out). You can now use `source.baseUrl` prop to achieve that purpose.

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).
