### ISSUE TITLE
How do I style this li > p so it displays inline with the bullet?

### ISSUE THREAD

**Issue by rahul-desai3** [meliorence/react-native-render-html#228]
### Is this a bug report or a feature request?

A question actually

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

iOS and Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

    React: 16.5.0
    React native:https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
    react-native-render-html: ^4.1.1

    Target Platform:
    iOS (10.1, 10.2, 10.3)
    Android latest version

### Steps to Reproduce

Just load the page

### Expected Behavior

The bullets need to be inline with the text in `<p>`.

### Actual Behavior

The bullet and the li > p text are are separate lines.
I am not sure how to style it. I tried to use the snippets from the doc but it changed the bullet style and not the position. I didnt see anything specific about the position.

![image](https://user-images.githubusercontent.com/2539881/52891331-3269b580-313f-11e9-96ae-d19cef92e681.png)

### Reproducible Demo

Expo Snack link: https://snack.expo.io/HJihF0VBN

**Comment by AlexBrel** [comment]
Same issue for me!

**Comment by ally03** [comment]
same issue with me and I tried this way and it is working fine 

const tagsStyles = {
  p: {
    marginHorizontal: 20,
    marginBottom: 16,
    fontSize: 16,
  },
  h1: { marginHorizontal: 20, fontSize: 24,  },
  h2: { marginHorizontal: 20, fontSize: 22,  },
  h3: { marginHorizontal: 20, fontSize: 20,  },
  h4: { marginHorizontal: 20, fontSize: 18, },
};
tagsStyles={tagsStyles}
