### ISSUE TITLE
wrap children example needed

### ISSUE THREAD

**Issue by orhanveli** [meliorence/react-native-render-html#232]
### Is this a bug report or a feature request?

No

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

(Write your answer here.)

### Steps to Reproduce

Is there any way to wrap children with a tag. My HTML code has orphened li tags without ul-ol. I want them to wrap with ``<ul>...</ul>``

```js
{
    .....
    alterChildren: (node: any) => {
        const { children, name } = node;
        // if there is no ul|ol tag around li tags wrap them

        if (name === "td" && children && children.length) {
            const arr = Array.from(children);
            const hasli = arr.some((item: any, i) => {
                return item.name === "li";
            });
            if (hasli === true) {
                return // ???? wrapped children
            }
        }
    },
}
``` 

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

code example above

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by jsamr** [comment]
@orhanveli  This library uses `htmlparser2` to create a DOM. `htmlparser2` has utility libraries to do just that (see [domutils](https://github.com/fb55/domutils)). 

```js
import {Element} from 'domhandler';
import { appendChild } from 'domutils';

//

if (hasLi) {
  const wrapper = new Element('p');
  for (const child of children) {
    appendChild(wrapper, child)
  }
  return wrapper
}
```
