### ISSUE TITLE
How to limit content number line?

### ISSUE THREAD

**Issue by HarrisKoffi** [meliorence/react-native-render-html#243]
Hello,

How to limit html content number line like **react component Text** props numberofLine?
Thank you!

**Comment by lohithananda** [comment]
> Hello,
> 
> How to limit html content number line like **react component Text** props numberofLine?
> Thank you!

**Comment by lohithananda** [comment]
How can we use number of line prop for HTML

**Comment by Zjarr** [comment]
```
renderers={{
  p: (_, children, convertedCSSStyles, { allowFontScaling, key }) => {
    return (
      <Text numberOfLines={null} allowFontScaling={allowFontScaling} key={key} style={convertedCSSStyles}>{ children }</Text>
     );
   }
 }}
```

**Comment by OleksandrFomin** [comment]
> You can do it by creating this renderer and changing the numberOfLines **null** attribute to your desired number
> 
> ```
> renderers={{
>   p: (_, children, convertedCSSStyles, { allowFontScaling, key }) => {
>     return (
>       <Text numberOfLines={null} allowFontScaling={allowFontScaling} key={key} style={convertedCSSStyles}>{ children }</Text>
>      );
>    }
>  }}
> ```

It applies to each `<p>` tag of the in your HTML. I receive several `<p>` under separate `<h>`  tags and it shows the number of lines I enter from each paragraph. Is there any way to do that for the whole document in case it is NOT wrapped by any tag?

**Comment by jsamr** [comment]
I am closing because this will be resolved by #349.

**Comment by ao-tigran** [comment]
I wouldn't consider this one as resolved. Yes this solution works when you have text-only content, but in case there are nested block elements the view is getting corrupted. The reason is that View element cannot be nested into Text element.

**Comment by jsamr** [comment]
@ao-tigran With the powerful new foundry API (#430) you can do something like this (Typescript):

```tsx
import React from 'react';
import { Text } from 'react-native';
import RenderHtml, {
  TBlock,
  CustomBlockRenderer,
  TNodeChildrenRenderer
} from 'react-native-render-html';
import { SnippetDeclaration } from '../types';

// Change the HTML code here and see what happens.
const html = `
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  <img width="1200" height="800" src="https://i.imgur.com/XP2BE7q.jpg" />
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
`;

const ParagraphRenderer: CustomBlockRenderer = function ParagraphRenderer({
  TDefaultRenderer,
  tnode,
  ...props
}) {
  return (
    <TDefaultRenderer tnode={tnode} {...props}>
      <TNodeChildrenRenderer
        tnode={tnode}
        parentMarkers={props.markers}
        renderChild={({ childTnode, childElement }) =>
          childTnode instanceof TBlock ? (
            childElement
          ) : (
            <Text numberOfLines={3}>{childElement}</Text>
          )
        }
      />
    </TDefaultRenderer>
  );
};

const renderHtmlProps = {
  source: { html },
  renderers: {
    p: ParagraphRenderer
  }
};

// ...
<RenderHtml {...renderHtmlProps} />
```

Result: 
![Screenshot_1617100675](https://user-images.githubusercontent.com/3646758/112976155-e1ed2080-912a-11eb-981c-0d9b25994818.png)


Note that the `TNodeChildrenRenderer` API is not guaranteed to be stable yet, but the feature is here.

**Comment by castalonirenz** [comment]
This is not working on <span> tags

**Comment by castalonirenz** [comment]
![image](https://user-images.githubusercontent.com/13584669/118856622-bce68400-b909-11eb-9453-162d02a0c258.png)

On some of my <p> tags its working but as you can see on the image it doesn't work on the next item.

**Comment by jsamr** [comment]
@castalonirenz If will only work for direct children of `<p>` tags, since your tampering with the children in the ParagraphRenderer. i understand that it is a bit complex to grasp, I'm currently working on the documentation website which will, I hope, help clear some blur.

**PS**: Your problem is yet a bit ill-defined, but I am available for counseling if you or your company is willing to hire me.

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).

**Comment by jsamr** [comment]
@oferRounds see https://stackoverflow.com/a/69200348

**Comment by oferRounds** [comment]
Hi @jsamr, thank you! Will you be able to give an example? Not quite sure based on the example
(Our html tree contains multiple tag elements, and I don’t to limit it per tag, but limit the line number in general)

**Comment by MatkoMilic** [comment]
> Hi @jsamr, thank you! Will you be able to give an example? Not quite sure based on the example (Our html tree contains multiple tag elements, and I don’t want to limit it per tag, but limit the lines number in general)

I need the same thing, trying to figure it out rn

**Comment by gregoripolak** [comment]
Hi everyone, was there a solution to this?

I need all of the input to be limited by n number of lines, I don't see a way to do it generally.

I can setup renderers for each type, but this doesn't solve the issue of limiting all of the content.

**Comment by Alexadru** [comment]
@jsamr I'm looking for exactly the same thing @gregoripolak described. Is it possible using this library?
