### ISSUE TITLE
Advice/Doc: Decorating onParsed

### ISSUE THREAD

**Issue by thepian** [meliorence/react-native-render-html#293]
Based on the documentation it seems straight forward to add methods/data to nodes in onParsed and used it in alterData. That approach doesn't seem to work however. Is there a recommendation somewhere for how to do it?

**Comment by itokun99** [comment]
same issue, we need more doc or implementation about altering node in this library. please advice

**Comment by r3dm4n** [comment]
Still no docs.

**Comment by jsamr** [comment]
`onParsed` returns the root elements of the render tree (a temporary structure later translated to react elements). In the [documented example](https://github.com/archriss/react-native-render-html#onparsed), a "mycustomblock" element is added after the fourth root element. This element could also have a children property. There are no exposed functions to help end-user building this data structure yet. The transient data structure is being currently revised and formalized to account for a good amount of limitations, including whitespace collapsing, see RFC #421. We will provide a more elaborated documentation when these changes are implemented though.

**Comment by jsamr** [comment]
I am closing because the `onParsed` utility will be discontinued in the foundry release (v6).
