### ISSUE TITLE
Provide a nestLevel property to list prefix renderers

### ISSUE THREAD

**Issue by jsamr** [meliorence/react-native-render-html#312]
### Is this a bug report or a feature request?

Feature Request

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes.

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Description

Provide a `{ nestLevel }` property to list prefix renderers.

### Usage

``` typescript
const listsPrefixesRenderers = {
  ul: ({ nestLevel }) => {
    if (nestLevel === 0) return <Square />
    if (nestLevel === 1) return <Bullet />
    return <Triangle />
  }
}
```

**Comment by lyqht** [comment]
Agree with this

**Comment by pxmage** [comment]
Hey guys @lyqht @jsamr and anyone who runs into this problem.

I kind of figure out a work-around to share with you.

You could take advantage of [alterNode Feature](https://github.com/archriss/react-native-render-html#alternode)

try check this
```javascript
alterNode={(node) => {
  const { name, parent } = node;
  if(name === 'li') {
    console.log(getParentsTagsRecursively(node))
  }
}}
```

and you will get output like:
```javascript
["li", "ul", "li", "ul", "li", "ul"]
```
where there are all parent tags listed inside an array, then you count the number of `ul`s and you get the nested level.

You can do whatever you like to customize it :)
