### ISSUE TITLE
Last pragraph sentence of some html text gets cuts off i.e not shown

### ISSUE THREAD

**Issue by kamalpandey** [meliorence/react-native-render-html#360]
This is problem In smaller device in Android    i.e. Google pixel 2xl or 2a and not problem in larger device. Could somebody tell what is wrong?

**Comment by ohitslaurence** [comment]
Try add this to your props, worked for me.

```
customWrapper: (content) => {
    return <Text textBreakStrategy="simple">{content}</Text>;
},
```

**Comment by nolife08021** [comment]
> Try add this to your props, worked for me.
> 
> ```
> customWrapper: (content) => {
>     return <Text textBreakStrategy="simple">{content}</Text>;
> },
> ```

hi,
can you give me full sample?

**Comment by nolife08021** [comment]
> Try add this to your props, worked for me.
> 
> ```
> customWrapper: (content) => {
>     return <Text textBreakStrategy="simple">{content}</Text>;
> },
> ```

I tried, it cut off more content. lol

**Comment by nolife08021** [comment]
![Screen Shot 2020-05-09 at 5 59 12 PM](https://user-images.githubusercontent.com/49778835/81470726-f24c9200-921e-11ea-9eda-420310ee2662.png)

**Comment by nolife08021** [comment]
@kamalpandey  @ohitslaurence do you guys have any solution on this?

**Comment by nolife08021** [comment]
I tried 
`                            customWrapper={(content) => {return <TextInput  multiline={true} editable={false} selectTextOnFocus={false}>{content}</TextInput>;}}
`


An error show out. 

**Invariant Violation: Nesting of <View> within <Text> is not currently supported**

**Comment by kamalpandey** [comment]
@nolife08021 No Waiting for some one to reply on this.

**Comment by nolife08021** [comment]
@kamalpandey 

try this

`<HTML
                  tagsStyles={{p:{ flex:1 }}}
                  allowFontScaling={false}
                  customWrapper={(content) => {return <TextInput style={{backgroundColor:'white'}}   multiline={true}  editable={false} selectTextOnFocus={false}>{content}</TextInput>;}}
                  baseFontStyle={{flex:1, fontSize:14, fontFamily: "System"}} ignoredStyles={["font-family"]}
                  html={html}/>`

**Comment by ohitslaurence** [comment]
@kamalpandey Also try adding `lineHeight` to your html tags. Like 1.4x your font size

**Comment by nolife08021** [comment]
> @kamalpandey Also try adding `lineHeight` to your html tags. Like 1.4x your font size

lineHieght works for me. Thanks

**Comment by kamalpandey** [comment]
@nolife08021  @ohitslaurence 
I am using like this
` <HTML
        html={postBody}
        onLinkPress={handleLinkPress}
        imagesMaxWidth={imagesMaxWidth()}
        ignoredStyles={[...IGNORED_STYLES]}
        baseFontStyle={baseFontStyle()}
        alterChildren={node => alterChildren(node)}
        alterNode={node => alterNode(node)}
        staticContentMaxWidth={staticContentMaxWidth()}
      />`
where should i be using?

**Comment by ohitslaurence** [comment]
> @nolife08021 @ohitslaurence
> I am using like this
> ` <HTML html={postBody} onLinkPress={handleLinkPress} imagesMaxWidth={imagesMaxWidth()} ignoredStyles={[...IGNORED_STYLES]} baseFontStyle={baseFontStyle()} alterChildren={node => alterChildren(node)} alterNode={node => alterNode(node)} staticContentMaxWidth={staticContentMaxWidth()} />`
> where should i be using?

@kamalpandey You can put the `lineHeight` inside your baseFontStyle

**Comment by kamalpandey** [comment]
@ohitslaurence 
I added this 
```
const MOBILE_FONT_SIZE = 15;
export const baseFontStyle = () => {
  return {
    fontSize: isTablet ? TABLET_FONT_SIZE : MOBILE_FONT_SIZE,
    lineHeight: MOBILE_FONT_SIZE * 1.4,
    color: Colors.darker
  };
};
```
but still issue persists.

**Comment by nolife08021** [comment]
@kamalpandey 

I set the lineHeight in tagStyle.

`<HTML
                  allowFontScaling={false}
                  tagsStyles={{p:{fontSize:18, padding:10, minHeight:60, lineHeight:22 }}}
                  baseFontStyle={{fontSize:scaledSize(18), fontFamily: "System", justifyContent:'center' }} ignoredStyles={["font-family"]}
                  html={JSON.parse(optionText)} {...htmlConfig}/>`

**Comment by Tyki** [comment]
Facing same issues on MIUI and oneplus OS. 

Any updates?

**Comment by kamalpandey** [comment]
@Tyki 
For now you can use 
[https://github.com/archriss/react-native-render-html/pull/349]()

**Comment by jsamr** [comment]
So this bug has reportedly appeared with React Native on Android Q (https://github.com/facebook/react-native/issues/25258). Since v5 release, you can use `defaultTextProps` and set `textBreakStrategy` to `highQuality` in order to circumvent this bug. I'm closing this thread now as there is an easy workaround and the bug is upstream.

**Comment by hotaryuzaki** [comment]
> So this bug has reportedly appeared with React Native on Android Q ([facebook/react-native#25258](https://github.com/facebook/react-native/issues/25258)). Since v5 release, you can use `defaultTextProps` and set `textBreakStrategy` to `highQuality` in order to circumvent this bug. I'm closing this thread now as there is an easy workaround and the bug is upstream.

`defaultTextProps={{ textBreakStrategy: 'highQuality' }}`
not worked for me, set to simple not worked too.

**Comment by hotaryuzaki** [comment]
sorry, mine was v4 so i need to update to v5.
now it works, but i had to set to **simple**, not highQuality
`defaultTextProps={{ textBreakStrategy: 'simple' }}`

**Comment by aarie33** [comment]
any update on this issue?
I use v6.3.4, and I still have an issue with the last 2/3 of words in the last paragraph being cut off.

**Comment by mochadwi** [comment]
using both `simple` & `highQuality` not works for me using 6.3.4, with RN 0.68.2, in android 10 & above
