### ISSUE TITLE
baseFontStyle is not working with <li>

### ISSUE THREAD

**Issue by sayem314** [meliorence/react-native-render-html#414]
```jsx
<HTML html={post.html} contentWidth={width} baseFontStyle={{ color: 'white' }} />
```

font styles are not applied to li. example html:

```
<ol><li>Line 1</li><li>Line 2</li><li>Line 3 <a href="https://github.com/">LINK</a> Example</li></ol>
```

![screenshot-2020-10-01_01 47 02 484](https://user-images.githubusercontent.com/14138401/94732438-181e3300-0388-11eb-9ae9-f9963b63a7e9.png)

* Notice the numbers

**Comment by jsamr** [comment]
@sayem314 Probably similar to #165, but since it was closed I will keep your issue open! I agree this should be solved.

**Comment by Taggotty** [comment]
I managed to change the color using the code to fix the RTL issue #286. By exchanging the background color from black to the preferred color. Hope this helps.

**Comment by jsamr** [comment]
<table>
<tr>
<td valign="top">

This issue has been fixed in the Foundry release. Try it out now! See #430 for instructions.

</td>
<td width="300">
<img width="300" src="https://user-images.githubusercontent.com/3646758/100381340-90574c80-2ff7-11eb-8289-2a435a2e0798.png" />
</td>
</tr>
</table>

**Comment by harveyconnor** [comment]
@jsamr any plans to also support `list-style-type: "lower-roman" | "upper-roman"` ?
Cheers

**Comment by jsamr** [comment]
@harveyconnor not a priority but it should happen at some point!

**Comment by jsamr** [comment]
@harveyconnor Good news, support for roman is on its way: https://github.com/meliorence/react-native-render-html/issues/286#issuecomment-818347185
