### ISSUE TITLE
Percentage value for padding and margin crashes the application

### ISSUE THREAD

**Issue by kenken023** [meliorence/react-native-render-html#418]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### React Native

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 9.10 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

##### Libraries

- react-native-render-html: ^4.2.4
- react-native-webview: ^10.9.0

#### Devices

- Device 1 simulator (iPhone 11)
  * OS: iOS 13.6
  * Diagnostic:  reproduction
  * Environment: production and development

##### Description

When there are percentage value of margin or padding, the application crashes with the following error message:

```
Error setting property 'margin' of RCTVirtualText with tag #873: JSON value '19% 0' of type NSString cannot be converted to a YGValue. Did you forget the % or pt suffix?
2020-10-26 20:19:54.301581+0800 Wish1075[3183:72044] [native] Error setting property 'margin' of RCTView with tag #877: JSON value '19% 0' of type NSString cannot be converted to a YGValue. Did you forget the % or pt suffix?
2020-10-26 20:19:59.720127+0800 Wish1075[3183:71841] Returning local object of class NSString
```

(Write your steps here:)

1. Render the following code snippet
```
<HTML html={`<html><body><div style="padding: 19% 0;">The quick brown fox jumps over the lazy dog</div></body></html>`}
                  baseFontStyle={{ color: Colors.text }}
                  tagsStyles={tagsStyles}
                  imagesMaxWidth={Dimensions.get('window').width - 40} />
```
2. If there are percentage on padding, the application crashes

**Comment by jsamr** [comment]
This issue has been fixed in the Foundry release. Try it out now! See #430 for instructions.
