### ISSUE TITLE
How can I get a paragraph index, and insert some custom view below or above that ?

### ISSUE THREAD

**Issue by r3dm4n** [meliorence/react-native-render-html#419]
- [X ] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [ X] I have read the documentation here: https://git.io/JJcAl 
- [X ] I have confirmed that this bug has not been reported yet

I am trying to insert some custom views after some paragraphs. Is that something we are able to do ?
How can I get the index of an element?
How can I insert some custom view after or before that, without altering the text

Thank you

**Comment by jsamr** [comment]
This feature is available in the new Foundry release! Check out this PR #434, section *Example of "Children Tampering"*. The steps to test this new release are available in thread #430.
