### ISSUE TITLE
[6.x] 🚀 Welcoming the Foundry release!

### ISSUE THREAD

**Issue by jsamr** [meliorence/react-native-render-html#430]
<p align="center">
<strong>Foundry Status</strong><br/>

<img src="https://img.shields.io/npm/v/react-native-render-html/foundry" />
<img src="https://github.com/meliorence/react-native-render-html/workflows/CI/badge.svg?branch=dev%2Ffoundry" />
<img src="https://codecov.io/gh/meliorence/react-native-render-html/branch/dev%2Ffoundry/graph/badge.svg" /><br/>
<a href="https://github.com/meliorence/react-native-render-html/issues/434">Check the PR!</a>
</p>

> :warning: This post will be updated on a regular basis! First pre-release has been released in late November. As long as the README is not ready, development is occurring in the [dev/foundry](https://github.com/archriss/react-native-render-html/tree/dev/foundry) branch. Also note that the Foundry Playground app is versioned and regularly updated!

> :information_source:  **If you have ideas, suggestions or you dislike something in this pre-release, you're invited to comment in this thread:  [What do you dislike or believe is missing in Foundry?](https://github.com/meliorence/react-native-render-html/issues/462)**

> :information_source:  **If you'd like to report a bug, you can comment in this thread or ping us in our [Discord channel](https://discord.gg/dbEMMJM).**

<p align="center">
<a href="https://expo.io/@jsamr/projects/react-native-render-html-foundry-demo">
<img src="https://user-images.githubusercontent.com/3646758/99804672-1f58f600-2b1a-11eb-9a7d-9ac39403f7bd.jpg" width="400" />
</a>
</p>

Hello community! I have been working on the new "Foundry" release for a while now, and I have just published a demo on expo, ["Foundry Playground"](https://expo.io/@jsamr/projects/react-native-render-html-foundry-demo), where you can experiment with the new engine and its features. Please give us feedback!

## Testing Foundry Playground

1. Download the expo app on your smartphone ([iOS](https://apps.apple.com/app/expo-client/id982107779), [Android](https://play.google.com/store/apps/details?id=host.exp.exponent)).
2. Play with the demo:
    - **iOS**: [Open the project page](https://expo.io/@jsamr/projects/react-native-render-html-foundry-demo) from your smartphone and click "Open with Expo".
    - **Android**: [Open the project page](https://expo.io/@jsamr/projects/react-native-render-html-foundry-demo) from any device and scan the QR code to open with Expo.

### From Scratch

Be careful, a lot of breaking changes! A compat module will be released to ease the transition.

```
npm install --save react-native-render-html@foundry
```

Take a look at how to use the new renderer API here: https://github.com/archriss/react-native-render-html/pull/434#issue-527747509 (section "Renderer API") or take inspiration from [the demo snippets](https://github.com/archriss/react-native-render-html/tree/dev/foundry/demo/snippets).

#### Clone

Clone this repository, "dev/foundry" branch: 

```
git clone https://github.com/archriss/react-native-render-html.git --branch dev/foundry
cd react-native-render-html
```

#### Install

```
yarn install
```

#### Build

```
yarn build
```

#### Start the Playground App

```
yarn start
```

#### Test HTML Snippets on your own!

Play with [**demo/snippets/test.tsx**](https://github.com/archriss/react-native-render-html/blob/dev/foundry/demo/snippets/test.tsx) and change the `html` variable.

## A New Render Engine and CSS Processor

The new release should be significantly more reliable regarding styles and compliance with CSS / HTML standards. I have extracted two packages for this purpose: 

- `@native-html/css-processor`, which handles all the logic of translating CSS styles into native styles ;
- `@native-html/transient-render-engine`, which implements [RFC002](https://github.com/archriss/react-native-render-html/blob/master/rfc/002-CSS-whitespace-collapsing.adoc) and is in charge of creating a data structure ready for rendering.

Both packages are available in the [`@native-html/core`](https://github.com/native-html/core#readme) project monorepo. These packages are heavily tested against standards.

## Features Highlight

**See https://github.com/archriss/react-native-render-html/pull/434#issue-527747509**

## Demo

In the demo app, you can toggle the legacy (5.x) vs Foundry (6.x) modes with the **L** button below. You can inspect the HTML source, and even the Transient Render Tree structure.  [**Try out the demo here**](https://expo.io/@jsamr/projects/react-native-render-html-foundry-demo).

<table>
  <thead>
    <tr>
      <th>Foundry / Legacy Modes</th>
      <th>HTML Source / Transient Render Tree</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <img
          width="400"
          src="https://user-images.githubusercontent.com/3646758/99916297-2b92ae00-2ce8-11eb-9116-c74b23a35404.png"
        />
        <br />
        <img
          width="400"
          src="https://user-images.githubusercontent.com/3646758/99916306-38af9d00-2ce8-11eb-8a36-a2cad2c5bd1d.png"
        />
      </td>
      <td valign="top">
        <img
          width="400"
          src="https://user-images.githubusercontent.com/3646758/99916319-4a914000-2ce8-11eb-88f6-8dd78a3f9009.png"
        />
        <br />
        <img
          width="400"
          src="https://user-images.githubusercontent.com/3646758/99916329-5b41b600-2ce8-11eb-8c0b-26808f90523a.png"
        />
      </td>
    </tr>
  </tbody>
</table>

And a few extra screenshots

<table>
  <thead>
    <tr>
      <th>Drawer Menu</th>
      <th>Images</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <img
          width="400"
          src="https://user-images.githubusercontent.com/3646758/99916373-b5427b80-2ce8-11eb-967e-a5d74cbfe2ae.png"
        />
      </td>
      <td>
        <img
          width="400"
          src="https://user-images.githubusercontent.com/3646758/99916365-ad82d700-2ce8-11eb-84bb-5aa6d8cc7817.png"
        />
      </td>
    </tr>
  </tbody>
</table>

## Progress

Check the "Remaining Work" section here: https://github.com/archriss/react-native-render-html/pull/434

## Credits

Kudos to [Expensify](https://www.expensify.com) company which has hired me to work on the white space collapsing challenge, without which I would not have been able to commit full bandwidth those last 2 weeks! A great gift to the Open Source community. If you are an expert React Native contractor, they might have work for you (reactnative [at] expensify.com).

**Comment by M1ck0** [comment]
For some reason, `iframe` is not rendered at all. Youtube embed is inside iframe, and it is not loaded. Any ideas what could be the problem?
@jsamr

**Comment by jsamr** [comment]
@M1ck0 Yes, iframes rendering is being extracted to a plugin (similar to tables), because we don't want to require consumers to depend on WebView. You can check the status of the work here: https://github.com/archriss/react-native-render-html/pull/434

**Comment by M1ck0** [comment]
@jsamr Is there a way to make them work with the current state of the package?

I tried downgrading it and it works, but then I am losing some bug fixes that are introduced in the Foundy release, which is not optimal solution

**Comment by M1ck0** [comment]
I made it work using custom renderers. I extracted URL from `iframe` and loaded it into `WebView` like this
```jsx
iframe: (htmlAttribs, children) => {
                console.log(JSON.stringify(htmlAttribs, null, 2));
                return (
                  <View>
                    <WebView
                      source={{ uri: htmlAttribs.tnode.attributes.src }}
                      style={{ flex: 1, width: width, height: 250 }}
                    />
                  </View>
                );
              },
```

I also needed to specify `width`, `height`, and `flex` for `WebView` because it wouldn't work on Android for some reason.

**Comment by jsamr** [comment]
@M1ck0 You could write a custom renderer (it scales automatically to available screen width, given you provide `contentWidth` prop to the `RenderHTML` component). Example with this html:

```html
<p>
<iframe width="560"
        height="315"
        src="https://www.youtube.com/embed/POK_Iw4m3fY"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
</iframe>
</p>
```

> **:warning: Make sure you use the latest release (6.0.0-alpha.9) to gain access to `useSharedProps` hook!**

<table>
<tr>
<th  width="300">Code</th>
<th >Rendered</th>
</tr>
<tr>
<td>

```jsx
import React from 'react';
import {
  useSharedProps,
  defaultHTMLElementModels
} from 'react-native-render-html';
import WebView from 'react-native-webview';
import { SnippetDeclaration } from '../types';

function extractPrintDimensions({
  attrWidth,
  attrHeight,
  styleWidth,
  styleHeight,
  contentWidth
}) {
  let printWidth, printHeight;
  let ratio;
  if (typeof attrWidth === 'number' && typeof attrHeight === 'number') {
    ratio = attrWidth / attrHeight;
  } else if (
    typeof styleWidth === 'number' &&
    typeof styleHeight === 'number'
  ) {
    ratio = styleWidth / styleHeight;
  } else {
    ratio = 16 / 9;
  }
  printWidth = Math.min(
    contentWidth,
    typeof attrWidth === 'number'
      ? attrWidth
      : typeof styleWidth === 'number'
      ? styleWidth
      : contentWidth
  );
  printHeight = printWidth / ratio;
  return {
    printWidth,
    printHeight
  };
}

function IframeRenderer({ tnode, style, key }) {
  const { contentWidth } = useSharedProps();
  const { width, height, ...restStyle } = style;
  const attrWidth = Number(tnode.attributes.width);
  const attrHeight = Number(tnode.attributes.height);
  const { printWidth, printHeight } = extractPrintDimensions({
    attrWidth: Number.isNaN(attrWidth) ? null : attrWidth,
    attrHeight: Number.isNaN(attrHeight) ? null : attrHeight,
    styleWidth: width,
    styleHeight: height,
    contentWidth
  });
  const source = tnode.attributes.srcdoc
    ? { html: tnode.attributes.srcdoc }
    : { uri: tnode.attributes.src };
  return (
    <WebView
      key={key}
      source={source}
      style={{ ...restStyle, width: printWidth, height: printHeight }}
    />
  );
}

IframeRenderer.model = defaultHTMLElementModels.iframe;

const renderers = {
  iframe: IframeRenderer
}
```
Then, make sure you pass `renderers` as a prop to the `RenderHTML` component.

</td>
<td valign="top" width="300" >

<img width="300" src="https://user-images.githubusercontent.com/3646758/100729029-06b4cf80-33a7-11eb-959f-1e9203b30253.png" />

</td>
</tr>
</table>

**Comment by brayanarrieta** [comment]
Hello @jsamr in the case I want to use the version with the whitespace fixed, what version need to use?

**Comment by jsamr** [comment]
@brayanarrieta Just install the package with the foundry tag:

```
npm install --save react-native-render-html@foundry
```
Be aware, this is still an unstable version subject to API changes. There are quite a lot of breaking changes with the previous release, read the full post above for an overview https://github.com/meliorence/react-native-render-html/issues/430#issue-747058610

**Comment by brayanarrieta** [comment]
> @brayanarrieta Just install the package with the foundry tag:
> 
> ```
> npm install --save react-native-render-html@foundry
> ```
> 
> Be aware, this is still an unstable version subject to API changes. There are quite a lot of breaking changes with the previous release, read the full post above for an overview [#430 (comment)](https://github.com/meliorence/react-native-render-html/issues/430#issue-747058610)

thanks @jsamr

**Comment by Aparus** [comment]
I'm trying to refactor [my code from v5](https://github.com/meliorence/react-native-render-html/issues/442#issuecomment-769842562) in new way .... but I have so many errors and questions. 

In custom renderer: 
What should i use instead of `htmlAttribs ` --  `tnode.attributes` ?  
What should i use instead of `children` (2nd argument of renderer). From where should I get it? I've tried `tnode.children` it doesn't work...  

What is RenderHTML? Sorry I didn't find any examples with it. Is it default export of `RNRH`? 

That's what I did: 

```jsx
	const quizRenderer = ({ tnode, style, key }) => {
		const {
			attributes: { type, quizid: quizId },
			children
		} = tnode
		return <View key={key}>{children}</View>
	}
	quizRenderer.model = defaultHTMLElementModels.div

	const variantRenderer = ({ tnode, style, key }) => {
		const {
			attributes: { quizid: quizId, variantid: variantId, type },
			children
		} = tnode

		// const { userAnswers } = useSharedProps()

		return (
			<TouchableOpacity
				key={key}
				onPress={handlePressQuizVariant(quizId, variantId)}
			>
				<Text>
					<CheckBox
						size={18}
						checked={userAnswers[quizId].includes(variantId)}
						containerStyle={{ margin: 0, padding: 0 }}
					/>
					{children}
				</Text>
			</TouchableOpacity>
		)
	}
	variantRenderer.model = defaultHTMLElementModels.div

	return (
		<View style={{ padding: 5 }}>
			<HTML
				renderers={{
					quiz: quizRenderer,
					variant: variantRenderer
				}}
				source={{ html }}
				contentWidth={contentWidth}
			/>
		</View>
	)
```

I faced error: 
```
Uncaught Error: Objects are not valid as a React child (found: object with keys {type, styles, attributes, contentModel, elementModel, children, domChildren, tagName, className, id, parentStyles, hasWhiteSpaceCollapsingEnabled, displayName}). If you meant to render a collection of children, use an array instead.
```
Then I tried `children.domChildren` and `children.children`, error disappeared, but children doesn't appear.

**Comment by jsamr** [comment]
@Aparus I totally understand that refactoring custom renderers is not obvious, and a thorough guide will be provided for the stable release. The `children` key of `tnode` object is not an array of react elements, but an array of transient nodes! 

> Uncaught Error: Objects are not valid as a React child (found: object with keys {type, styles, attributes, contentModel, elementModel, children, domChildren, tagName, className, id, parentStyles, hasWhiteSpaceCollapsingEnabled, displayName}). If you meant to render a collection of children, use an array instead.

So you should use `TNodeChildrenRenderer` to render transient children nodes instead of `children`.

```jsx
<TNodeChildrenRenderer tnode={tnode} />
```

>  What should i use instead of htmlAttribs -- tnode.attributes ?
Absolutely!

> I guess RenderHTML is default export of RNRH. Right?
Yes!

## Important remarks

When creating custom renderers, the preferred pattern is to use `TDefaultRenderer` prop component passed to the renderer in order to inherit styles from `classesStyles`, `tagsStyles` and inline styles (style attribute). A big extra is that `TDefaultRenderer` is guaranteed to support `onPress` prop! An other extra: you can pass `viewProps` and `textProps` which will be passed to the underlying `View` or `Text` depending on the rendered react native element (which is decided by the transient render engine). You can take inspiration [in this example](https://github.com/meliorence/react-native-render-html/blob/1a764e22bbe91eb0d5e35afc35bc00d244321c12/demo/snippets/customRenderers.tsx#L111).

**Comment by Aparus** [comment]
@jsamr , thank you! I did it. Now code looks more messy. But somehow it works. And rerendering works! 👍
I will learn more. And if I stuck somewhere I hope you don't leave me. 

![Peek 2021-01-29 22-21](https://user-images.githubusercontent.com/1222611/106318470-0b9bdf80-6281-11eb-9531-f2ff1b8d21dc.gif)

**Comment by jsamr** [comment]
**A note to participants:**  If you have ideas, suggestions or you dislike something in this pre-release, you're invited to comment in this thread:  [What do you dislike or believe is missing in Foundry?](https://github.com/meliorence/react-native-render-html/issues/462)

**Comment by twisger** [comment]
## 1.list marker invisible
### Current behavior
The default background color of ul list marker is white, So the `Disc` marker is invisible when background is white. 
### Requested Change
Marker default background color is black.


## 2.list marker alignment
### Current behavior
When a list item has a large font size, the marker will align with top line of font. It is different with web implementation (bottom line).
### Requested Change
Provide a props to controll alignment or keep consistent with web implementation.

## 3.pure text with line breaks
### Current behavior
Pure text with line breaks will render in single line, it will render multilple line text correctly in 5.x. 
### Requested Change
Render line breaks of pure text correctly.

**Comment by twisger** [comment]
@jsamr Thanks for your reply!

1. I test the ul list marker issue again on alpha.20 and found it still exist.I already remove alll tagStyle and classStyle.
<img width="455" alt="WX20210222-225136@2x" src="https://user-images.githubusercontent.com/12410710/108803275-4c2d0700-7568-11eb-88b5-775086aafe03.png">
I have to add a tag style to fix it.

```
const tagsStyles = {
  ul: {
    color: style.grays.black,
  },
} 
const contentWidth = useWindowDimensions().width
return (
  <HTML
    source={{
      html: `<ul><li>Hello world<ul><li>Sneaky<ul><li>Beaky</li><li>Like</li></ul></li></ul></li></ul>`,
    }}
    contentWidth={contentWidth}
    tagsStyles={tagsStyles}
  />
)

```

<img width="424" alt="WX20210222-234820@2x" src="https://user-images.githubusercontent.com/12410710/108803380-8a2a2b00-7568-11eb-9d4a-8aac2876e85d.png">

**Comment by jsamr** [comment]
@twisger Good catch, I'll fix that too!

**Comment by dennisbouwpas** [comment]
Is it possible to make a custom bullet with the new API? Trying to do something like this but don't know what to do next
```
const ul = ({ tnode, key }) => {
    return (
      <View key={key} style={{ borderWidth: 1, borderColor: 'red' }}>
        <TNodeChildrenRenderer tnode={tnode} />
      </View>
    );
  };
ul.model = defaultHTMLElementModels.div;
```

**Comment by jsamr** [comment]
@dennisbouwpas Not yet! But the feat is scheduled before stable.

**Comment by dennisbouwpas** [comment]
@jsamr Thanks for the quick reply !! 
Ok, I see. Do you have any ideas when the stable version will be ready?

**Comment by jsamr** [comment]
@dennisbouwpas As for now, you can at least chose the default bullet given an nest index thanks to `useInternalRenderer` hook. I listed the currently supported values in the below example:

```jsx
function getListStyleTypeFromNestLevel(index: number) {
  return 'circle'; // 'decimal' | 'disc' | 'square' | 'lower-latin' | 'upper-latin'
}

const CustomListRenderer = function ListRenderer(props) {
  const { Renderer, rendererProps } = useInternalRenderer('ul', props);
  return (
    <Renderer
      {...rendererProps}
      getListStyleTypeFromNestLevel={getListStyleTypeFromNestLevel}
    />
  );
};
```

As for a release data; that will depend on my bandwidth! But certainly before this summer.

**Comment by dennisbouwpas** [comment]
@jsamr Hmmm 🤔 that's better yes, but is it possible to style them a bit? For example, I need to make them a bit bigger and different color. Or is it possible to use an asset image to replace that bullet, like in regular CSS?

**Comment by jsamr** [comment]
@dennisbouwpas Not yet!

**Comment by amialone** [comment]
update text style when theme or color change

```
     baseStyle={{
        fontSize: textSize,
        fontFamily: 'System',
        whiteSpace: 'normal',
        color: textColor[theme]
      }}
```

**Comment by jsamr** [comment]
@amialone You should use `triggerTREInvalidationPropNames={['baseStyle']}`

**Comment by amialone** [comment]
@jsamr it works! thx 🙏

**Comment by and18aa** [comment]
I am trying to get figure tag with iframe working but i couldn`t find any solution till now.
This is my code: 
 ```

import WebView from 'react-native-webview';
import RenderHTML from 'react-native-render-html';
import IframeRenderer from '@native-html/iframe-plugin';
  const contentWidth = useWindowDimensions().width;
  const computeEmbeddedMaxWidth = (availableWidth) => {
    return Math.min(availableWidth, 500);
  };

  const renderers = {
    iframe: IframeRenderer,
  };
    <RenderHTML
              renderers={renderers}
              WebView={WebView}
              source={{html: props.route.params.htmlContent}}
              baseStyle={{color: '#fff', fontFamily: 'Tondo_A_Rg'}}
              onLinkPress={(event, href) => {
                Linking.openURL(href);
              }}
              renderersProps={{
                iframe: {
                  scalesPageToFit: true,
                  webViewProps: {
                    /* Any prop you want to pass to iframe WebViews */
                  },
                },
              }}
              contentWidth={contentWidth}
              computeEmbeddedMaxWidth={computeEmbeddedMaxWidth}
            />
```
Thank you for help

**Comment by jsamr** [comment]
@and18aa Would you mind providing [a snack](https://snack.expo.io/)? Especially, I would need to know 
- The html content
- The exact desired output
I suggest we continue this discussion [in our discord channel](https://discord.gg/dbEMMJM) to avoid notifying all subscribers to this ticket, thank you :smiley:

**Comment by thekalko** [comment]
#472

**Comment by jsamr** [comment]
For those of you who are interested in CSS counter styles (roman, arabic...), [**good news are reported here!**](https://github.com/meliorence/react-native-render-html/issues/286#issuecomment-818347185)

**Comment by adderly** [comment]
@jsamr 
Hello,

I can't seem to be able to use it in my code.

It's giving me this error: 
```
**Fri Apr 16 2021 10:31:54.882]  ERROR    Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.**
```

I used a striped down version of the examples just to try to make it work.

```
const HTMLComponent = React.memo(
    () => {

        return <RenderHTML
            enableExperimentalMarginCollapsing={true}
            debug={false}
            triggerTREInvalidationPropNames={['baseStyle']}
        />;
    }
);
```

**Comment by jsamr** [comment]
@adderly It's unlikely (though not impossible) that we have a hook misbehavior since the project is covered with the rules of hooks Eslint rules. [The most likely causes are explained here.](https://reactjs.org/warnings/invalid-hook-call-warning.html). If however you're confident that the problem comes from this library, please share a reproduction in the form of a [snack](https://snack.expo.io), or a git project.

**Comment by adderly** [comment]
> @adderly It's unlikely (though not impossible) that we have a hook misbehavior since the project is covered with the rules of hooks Eslint rules. [The most likely causes are explained here](https://reactjs.org/warnings/invalid-hook-call-warning.html). If however you're confident that the problem comes from this library, please share a reproduction in the form of a [snack](https://snack.expo.io), or a git project.

You are correct @jsamr , i created a new project and it worked. 

But in my current codebase it just doesn't work.

**Comment by jsamr** [comment]
@adderly Probably a duplicated `react` package, happened to me on a yarn 2 monorepo. If you're using yarn, you can try `yarn why react`; with npm `npm ls react` to identify the origin of the duplicated module. [See this guide.](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react). I'd rather not continue this discussion here to avoid spamming all subscribers. Feel free to join our discord if you have any question.

**Comment by nadav2051** [comment]
Hi! Thanks for the great job! not sure where to open bugs regarding Foundry issues, but I've tried to test the RTL with 6.0.24-alpha and it's not 100%,
My code:
`		return (
			<HTML
				source={{ html: this.props.htmlSource }}
				imagesMaxWidth={Dimensions.get('window').width}
				alterChildren={this.alterChildren.bind(this)}
				textSelectable
	                        WebView={WebView}
	                        renderersProps={{
	                        ol: { enableExperimentalRtl: true },
	                        ul: { enableExperimentalRtl: true }
}}/>
		);`

HTML Source:
`<body>
                                    <p>English - bullets</p>
<p>&nbsp;</p>
<p style="text-align: center;">Center</p>
<ul style="text-align: center;">
<li dir="ltr">Hello</li>
<li dir="ltr">world</li>
</ul>
<p dir="ltr" style="text-align: center;">&nbsp;</p>
<p>&nbsp;</p>
<p>Left</p>
<ul>
<li>Hello</li>
<li>world</li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p dir="rtl" style="text-align: right;">Right</p>
<ul dir="rtl" style="text-align: right;">
<li>Hello</li>
<li>world</li>
</ul>
<p dir="rtl" style="text-align: right;">&nbsp;</p>
                                </body>
`

react-native-render-html:
![image](https://user-images.githubusercontent.com/6547468/115200521-fc4c6580-a0fc-11eb-9f86-147fafc8726f.png)

[https://html-online.com/editor/](https://html-online.com/editor/):
![image](https://user-images.githubusercontent.com/6547468/115200611-12f2bc80-a0fd-11eb-90d7-8bc3dad08e61.png)

**Comment by jsamr** [comment]
@nadav2051 It's totally appropriate to comment in this thread for Foundry bug reports! I however prefer snacks as it's very fast to reproduce. Also, it would be nice to add in which platform the bug appears. On my end, I didn't manage to reproduce the RTL issue neither on Android (10), nor on iOS (14.4). See the repro I used here: https://snack.expo.io/@jsamr/rnrh-alpha24-rtl-repro

As per the centering issue, worth investigating. I'll take a look.

**Comment by adderly** [comment]
> > @adderly It's unlikely (though not impossible) that we have a hook misbehavior since the project is covered with the rules of hooks Eslint rules. [The most likely causes are explained here](https://reactjs.org/warnings/invalid-hook-call-warning.html). If however you're confident that the problem comes from this library, please share a reproduction in the form of a [snack](https://snack.expo.io), or a git project.
> 
> You are correct @jsamr , i created a new project and it worked.
> 
> But in my current codebase it just doesn't work.

Solved it with this. I think it is related to react-native-web coming from expo.

https://github.com/facebook/react/issues/13991#issuecomment-830308729

**Comment by castalonirenz** [comment]
onLinkPress is not working on the foundry version.

im trying to console the function.

![image](https://user-images.githubusercontent.com/13584669/118617124-e95cac00-b7f4-11eb-9867-e3bcbca63b9e.png)

**Comment by jsamr** [comment]
@castalonirenz `onLinkPress` has been moved to `renderersProps.a.onPress` [since version 6.0.0-alpha.23](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-alpha.23)

**Comment by castalonirenz** [comment]
@jsamr Hi, only the attributes ref is being get from the props. How can i get the text that has been press by the user?

**Comment by jsamr** [comment]
@castalonirenz Not an obvious solution at the moment, although we could pass the `TNode` instead of attributes, so that you can freely inspect its children. Right now, you could mangle the dom via dom visitors, and setting a `data-text` attribute:

```js
import { getText } from "domutils";

const domVisitors = {
  onElement(element) {
    if (element.tagName === "a") {
      element.attributes["data-text"] = getText(element);
    }
  },
};
```
Now you will have a `data-text` attributes passed to your `onPress` callback.

**Comment by castalonirenz** [comment]
> @castalonirenz Not an obvious solution at the moment, although we could pass the `TNode` instead of attributes, so that you can freely inspect its children. Right now, you could mangle the dom via dom visitors, and setting a `data-text` attribute:
> 
> ## alpha.25
> ```js
> import { getText } from "domutils";
> 
> const domVisitors = {
>   onElement(element) {
>     if (element.tagName === "a") {
>       element.attributes["data-text"] = getText(element);
>     }
>   },
> };
> ```
> 
> ## alpha.24 and below
> ```js
> import { getText, isTag } from "domutils";
> 
> function alterDOMNode(node) {
>   if (isTag(node) && node.tagName === "a") {
>     node.attributes["data-text"] = getText(node);
>   }
> }
> ```
> 
> Now you will have a `data-text` attribute passed to your `onPress` callback.

i will try this one and will give you an update in the next day. thanks for the reply appreciate it!

**Comment by castalonirenz** [comment]
@jsamr Where would i put this function inside my components? sorry i'm bit confused.

**Comment by castalonirenz** [comment]
> @castalonirenz Not an obvious solution at the moment, although we could pass the `TNode` instead of attributes, so that you can freely inspect its children. Right now, you could mangle the dom via dom visitors, and setting a `data-text` attribute:
> 
> ## alpha.25
> ```js
> import { getText } from "domutils";
> 
> const domVisitors = {
>   onElement(element) {
>     if (element.tagName === "a") {
>       element.attributes["data-text"] = getText(element);
>     }
>   },
> };
> ```
> 
> ## alpha.24 and below
> ```js
> import { getText, isTag } from "domutils";
> 
> function alterDOMNode(node) {
>   if (isTag(node) && node.tagName === "a") {
>     node.attributes["data-text"] = getText(node);
>   }
> }
> ```
> 
> Now you will have a `data-text` attribute passed to your `onPress` callback.

this is working see my screenshot

![image](https://user-images.githubusercontent.com/13584669/118686933-0dd97800-b837-11eb-88b5-05abab7e24ea.png)

**Console:**
![image](https://user-images.githubusercontent.com/13584669/118687001-1fbb1b00-b837-11eb-841a-04b6b8befcbe.png)

**Comment by castalonirenz** [comment]
Is there any numberOfLines for this?

**Comment by jsamr** [comment]
@castalonirenz See https://github.com/meliorence/react-native-render-html/issues/243#issuecomment-810114785

**Comment by castalonirenz** [comment]
> @castalonirenz See [#243 (comment)](https://github.com/meliorence/react-native-render-html/issues/243#issuecomment-810114785)

This is not working with <span> but working fine on <p> tag.

**Comment by jsamr** [comment]
@nadav2051 Regarding the centering issue, there is unfortunately nothing I can do since `textAlign` will only target `Text` elements, and the marker box where the counter is printed is wrapped in a `View`... consider this a "React Native barrier".

**Comment by jsamr** [comment]
Hi everyone! Good news, **The Beta is out!** [Check this ticket](https://github.com/meliorence/react-native-render-html/issues/489).
I'm closing this thread; and I want to say a big thanks to anyone participating in the alpha :heart:.
