### ISSUE TITLE
Error while updating property padding in shadow node of type: RCTView

### ISSUE THREAD

**Issue by M1ck0** [meliorence/react-native-render-html#432]
## Description
Few things are bugging me here.

This crash is happening at random times, in development, and when the app is built for production.

Content is loaded from WordPress using `react-native-render-html` and app is crashing because some styles are set inline in API response. I tried overwriting it with custom styling div tag like this

```
tagsStyles={{
  div: {
    padding: 0,
  }
}}
```
But it didn't work as expected

![image](https://i.stack.imgur.com/RnpLU.png)

## React Native version:
```
System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
    Memory: 1.52 GB / 15.56 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.2.1 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 3.8.6 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

Is there any other way that I can overwrite some styling, or remove them when injecting HTML.

**Comment by jsamr** [comment]
@M1ck0 All those inline issues will be fixed in the Foundry release, see #430. In the meantime, you can disable the padding rule with `ignoredStyles=['padding']` prop.

**Comment by M1ck0** [comment]
Okay great. Thank you a lot :)

**Comment by M1ck0** [comment]
Apparently, this is not a fix. After setting 'padding' to ignored styles I got this error

![image](https://user-images.githubusercontent.com/19279947/99938630-823fcc80-2d68-11eb-999e-3dfe3d0c86ec.png)

**Comment by jsamr** [comment]
@M1ck0 It is not obvious that the error is raised by this library. If you can provide a reproduction, I'll be happy to investigate. See [our contributing guide!](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc)

**Comment by M1ck0** [comment]
I will give you a reproduction as soon as possible. 

What can I say is that data I set into `html` comes from WordPress, and after investigating the response I saw few `<div>` tags have `padding: 19% 0` (as shown in first error), and after setting padding in `ignoredStyles` second error happens. 

I also have `width` and `height` in the ignored styles array, and they work perfectly.

**Comment by jsamr** [comment]
@M1ck0 If you're willing to give me the wordpress link, or share privately, I can test it in the new engine! Are you using renderers prop?

**Comment by M1ck0** [comment]
Where can I send you the link for API?

I am using renderers prop for the image only, to wrap them in a custom component for optimization.

**Comment by jsamr** [comment]
@M1ck0 Go on my GH profile, you'll see an email address ;-)

**Comment by M1ck0** [comment]
@jsamr Sent

**Comment by jsamr** [comment]
This issue has been fixed in the Foundry release. Try it out now! See #430 for instructions.

**Comment by M1ck0** [comment]
This is great. Thank you for your time and I am sorry for any inconvenience I caused.

Thank you so much.

**Comment by jsamr** [comment]
@M1ck0 No worries :-) You're welcome. Feel free to post for feedback, either here or on the #430 post!

**Comment by M1ck0** [comment]
I am not sure where to post this, but I have a question.

By default `head` and `script` tags are ignored. Is there a way to override this?

In my case, the client is using an external player for the video that is loaded with a `script` tag.

@jsamr

**Comment by M1ck0** [comment]
Quick question.

In some responses, I have a `script` tag that loads certain video player. Is there a way to extract `src` from that script tag?

I need to use that src and load it into `iframe`.

Is this achievable? I am trying to use `renderers` to extract the `script` tag but I can't get it to work. It is not outputting `children` in `console.log()`.

**Comment by jsamr** [comment]
@M1ck0 Good point, `script` and `styles` elements are special nodes handled differently by the underlying `htmlparser2` library, and the current version of `@native-html/transient-render-engine` doesn't handle those special nodes. Can you open a separate feature request ticket so that I keep track of the feature?

When the script tag is supported, its `contentModel` will still be `HTMLContentModel.none` (which means, non-displayable, ignored by the render library). At that point, you can override this model by doing the following:

```ts
import {
  defaultHTMLElementModels,
  HTMLContentModel,
} from "react-native-render-html";

function ScriptRenderer() {
  // do stuff
}

ScriptRenderer.model = defaultHTMLElementModels.script.extend({
  // default contentModel would be "none" for script, so we must override
  // the model.
  contentModel: HTMLContentModel.block,
});

const renderers = {
  script: ScriptRenderer,
};
```
