### ISSUE TITLE
Adding support for manipulating script tag

### ISSUE THREAD

**Issue by M1ck0** [meliorence/react-native-render-html#439]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have checked that the feature request has not been offered yet

### Decision table

- [x] The change I am requesting does not concern performance
- [x] The change I am requesting does not concern security
- [x] The change I am requesting does not concern code style
- [x] The change I am requesting does not concern development tooling and
  packaging and other “meta” features
- [x] The change I am requesting does not concern third-party deprecations  

### Feature

In some responses, I have a script tag that loads certain video player. Is there a way to extract src from that script tag?

I need to use that src and load it into an iframe.

Is this achievable? I am trying to use renderers to extract the script tag but I can't get it to work. It is not outputting children in console.log().

As mentioned in comments in #432

**Comment by castalonirenz** [comment]
no update on this library?

**Comment by jsamr** [comment]
We are now migrating feature requests to our new canny. Closing, but [you can track this feature here.](https://native-html.canny.io/features/p/support-script-tags).
