### ISSUE TITLE
Targetting plain text with tagsStyles 

### ISSUE THREAD

**Issue by robfuncken** [meliorence/react-native-render-html#452]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have checked that the feature request has not been offered yet

### Decision table

- [x] The change I am requesting does not concern performance
- [x] The change I am requesting does not concern security
- [x] The change I am requesting does not concern code style
- [x] The change I am requesting does not concern development tooling and
  packaging and other “meta” features
- [x] The change I am requesting does not concern third-party deprecations  

### Feature

I have some HTML content that is not encapsulated in a HTML tag. It is just plain text. I cannot find a way to target this text for styling with the tagsStyles property., 

So I would like to be able to define base styling for text that is not inside any html element.

ie. 
html={'This is plain-text and I am not able to target this or style this with tagsStyles '}

**Comment by jsamr** [comment]
@robfuncken This feature is already available in the foundry pre-release (see #434), via the `baseStyle`prop. This prop supports text-targeting style rules. Thus I am going to close this issue!
