### ISSUE TITLE
fail render figure

### ISSUE THREAD

**Issue by kh71** [meliorence/react-native-render-html#454]
fail render figure. how to set tag style

`<figure id=\"attachment_6129\" aria-describedby=\"caption-attachment-6129\" style=\"width: 800px\" class=\"wp-caption alignnone\"><img loading=\"lazy\" class=\"wp-image-6129 size-full\" src=\"https://i2.wp.com/orkunsantepheap.com/wp-content/uploads/2021/01/564000000747001.jpg?resize=696%2C464&#038;ssl=1\" alt=\"\" width=\"696\" height=\"464\" srcset=\"https://i2.wp.com/orkunsantepheap.com/wp-content/uploads/2021/01/564000000747001.jpg?w=800&amp;ssl=1 800w, https://i2.wp.com/orkunsantepheap.com/wp-content/uploads/2021/01/564000000747001.jpg?resize=768%2C512&amp;ssl=1 768w, https://i2.wp.com/orkunsantepheap.com/wp-content/uploads/2021/01/564000000747001.jpg?resize=150%2C100&amp;ssl=1 150w, https://i2.wp.com/orkunsantepheap.com/wp-content/uploads/2021/01/564000000747001.jpg?resize=300%2C200&amp;ssl=1 300w, https://i2.wp.com/orkunsantepheap.com/wp-content/uploads/2021/01/564000000747001.jpg?resize=600%2C400&amp;ssl=1 600w, https://i2.wp.com/orkunsantepheap.com/wp-content/uploads/2021/01/564000000747001.jpg?resize=696%2C464&amp;ssl=1 696w, https://i2.wp.com/orkunsantepheap.com/wp-content/uploads/2021/01/564000000747001.jpg?resize=630%2C420&amp;ssl=1 630w\" sizes=\"(max-width: 696px) 100vw, 696px\" data-recalc-dims=\"1\" /><figcaption id=\"caption-attachment-6129\" class=\"wp-caption-text\">នាវាចម្បាំង​ផ្ទុក​យន្តហោះ ធី​អូ​ដ័​រ រូ​ស្វ៊ែ​លត៍ របស់​សហរដ្ឋអាមេរិក ត្រៀម​ចូល​ប្រចាំការ​នៅ​សមុទ្រ​ចិន​ខាងត្បូង</figcaption></figure>`

![2021-01-28 13 30 42](https://user-images.githubusercontent.com/14502805/106099334-149b8c80-616d-11eb-90fc-a6b57cfebf6e.jpg)

**Comment by jsamr** [comment]
This report does not follow [our contribution guidelines](https://github.com/meliorence/react-native-render-html/blob/master/CONTRIBUTING.adoc#tickets) and I will close it as a consequence. Please feel free to reopen a new ticket while following the template and our guidelines.
