### ISSUE TITLE
Can't style with class

### ISSUE THREAD

**Issue by dzpt** [meliorence/react-native-render-html#455]
```
figure.image td {
        padding: 0px !important;
        margin: 0px !important;
        background-color: transparent !important;
        border-bottom: 0px !important;
    }
```

`<figure class='image'><table><tr><td><img src="..."/></td></tr><tr><td> </td></tr></table></figure>`

won't apply to `td` tag

**Comment by jsamr** [comment]
This is a duplicate of #437, this library doesn't claim support for cascading style sheets (yet). Closing now.

**Comment by dzpt** [comment]
@jsamr oh, i'm using table plugin, so this is the wrong package report.
it has `cssRules` attribute

**Comment by jsamr** [comment]
@dzpt No worries :-), feel free to resubmit in the appropriate issue tracker.
