### ISSUE TITLE
android app crash on back press please resolved it 

### ISSUE THREAD

**Issue by aamiryameen** [meliorence/react-native-render-html#458]
### Oath

I swear that I have completed these tasks before submitting:

- [ ] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [ ] I have read the documentation here: https://git.io/JJcAl 
- [ ] I have confirmed that this bug has not been reported yet

### Decision table

- [ ] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [ ] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### React Native

```

```

##### Libraries

- react-native-render-html:
- react-native-webview:

#### Devices

- Device 1 
  * OS: 
  * Diagnostic: 
  * Environment: 
- Device 2 
  * OS: 
  * Diagnostic: 
  * Environment: 

##### Description

(Write your steps here:)

1.
2.
3.

(Describe the expected outcome, and compare it to the observed outcome. You are
encouraged to join screenshots and screencasts, or pictures of the rendering
tree from debugging tools such as flipper)

##### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant
source code. When deemed appropriate, provide instructions to reproduce the
issue.)

(If you plan to provide a Regression Test PR, just leave a line written
*Planned Regression Test* and link it here when it's ready. We will be happy to
provide you help with crafting the test on our Discord #contributing channel.)

**Comment by jsamr** [comment]
See my comment in https://github.com/native-html/plugins/issues/29
