### ISSUE TITLE
iframe with youtube video is not rendered

### ISSUE THREAD

**Issue by florinleu** [meliorence/react-native-render-html#459]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

Installed libraries:
"react-native": "0.63.4"
"react-native-render-html": "^5.0.1"
"react-native-webview": "^11.2.1"

Html content I'm using is:
```
const htmlContent = `
    <html>
        <body>
            <div class="section">
                <div class="wrapper">
                    <h1>The TITLE</h1>
                    <div class="post-wrapper">
                        <div class="post-rich-text w-richtext">
                            <p>Check out this video to see it in action.</p>
                            <iframe allowfullscreen="true" frameborder="0" scrolling="no" src="//www.youtube.com/embed/zUvUjs0GcvQ" width="300" height="200"></iframe>
                            <p>And there’s even more to come... </p>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </html>`
```

```
<HTML
   tagsStyles={css}
   classesStyles={css}
   source={{ html: htmlContent }}
/>
```

The result:
![image](https://user-images.githubusercontent.com/1244065/106903101-3dd69280-6702-11eb-88e5-a3ab911c52b8.png)

As you can see the video is not rendered. I'm testing on an iOS simulator.

Any help would be appreciated. Thanks!

**Comment by jsamr** [comment]
@florinleu Please follow closely our template. [There is a note on our HELP document regarding iframes, in the "Common issues" section](https://github.com/meliorence/react-native-render-html/blob/master/HELP.adoc#common-issues). Closing!

**Comment by skizzo** [comment]
@jsamr thanks, there is no such section in the docs you referred to. Trying to render a YouTube iframe as well. Thanks for any hints and this great library :)
