### ISSUE TITLE
Passing uri in source fails this check

### ISSUE THREAD

**Issue by jimbofoo** [meliorence/react-native-render-html#461]
https://github.com/meliorence/react-native-render-html/blob/77b7599d8ebd5c0863f73f8c98779159f99ce8ec/src/HTML.js#L206

Should probably be:

} else if (uri) {
...
}

**Comment by jsamr** [comment]
@jimbofoo Should be fixed in  the [5.1.0](https://github.com/meliorence/react-native-render-html/releases/tag/v5.1.0) release.
