### ISSUE TITLE
Property 'index' does not exist on type 'PassProps{}>'

### ISSUE THREAD

**Issue by egor-sorokin** [meliorence/react-native-render-html#463]
### Oath

I swear that I have completed these tasks before submitting:

- [x ] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x ] I have read the documentation here: https://git.io/JJcAl 
- [x ] I have confirmed that this bug has not been reported yet

### Decision table

- [ x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [ x] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### React Native

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 988.40 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.0/12A8189n - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

##### Libraries

- react-native-render-html: ^4.2.1
- react-native-webview:

#### Devices
- not device-related

##### Description
I am using typed version of react-native-render-html, and trying to overwrite ordered list prefix, like so:
```
import { RendererDictionary } from 'react-native-render-html';

const listsPrefixesRenderers: RendererDictionary = {
  ol: (_htmlAttribs, _children, _convertedCSSStyles, passProps) => {
    return (
      <Text style={{ ...fonts.styles.body }}>
        {passProps.index + 1}
        {'. '}
      </Text>
    );
  }
}
```
Everything is working, but TS is throwing the following error `TS2339: Property 'index' does not exist on type 'PassProps{}>'.`

Expected behavior: index exists on type 'PassProps'

**Comment by jsamr** [comment]
@egor-sorokin I don't know which exact 4.x version you are using, but I just checked typings for 4.2.5 and the field should be `nodeIndex` instead of `index`.

**Comment by egor-sorokin** [comment]
@jsamr I just simply logged nodeIndex and index inside of `(_htmlAttribs, _children, _convertedCSSStyles, passProps)`
Seems `nodeIndex` is having an incorrect value

<img width="160" alt="Screenshot 2021-02-16 at 13 39 28" src="https://user-images.githubusercontent.com/13828339/108064033-65abeb80-705c-11eb-88a0-f906bde43d61.png">

**Comment by jsamr** [comment]
@egor-sorokin The 4.2.5 version you are using is unmaintained and we won't provide fixes. I suggest you switch to v5 (very few breaking changes, see #442) and if the issue still persists, I'm willing to provide a fix.

**Comment by egor-sorokin** [comment]
@jsamr thank you for the clarification, I will take a look!

**Comment by egor-sorokin** [comment]
@jsamr I just tried that out, and it's also an issue in v5

**Comment by dennisbouwpas** [comment]
Have this issue too
@egor-sorokin Did you find solution?
