### ISSUE TITLE
lineHeight for <ul> and <ol> is not work.

### ISSUE THREAD

**Issue by LimanASL** [meliorence/react-native-render-html#465]
### Oath

I swear that I have completed these tasks before submitting:

- [✓] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [✓] I have read the documentation here: https://git.io/JJcAl 
- [✓] I have confirmed that this bug has not been reported yet

### Decision table

- [✓] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [✓] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### React Native
react-native:0.63

##### Libraries

- react-native-render-html:"^5.1.0"
- react-native-webview:"^11.2.3"

#### Devices

- Device 1 simulator (iPhone X)
  * OS: iOS 14.4
  * Diagnostic: negative
  * Environment: development

##### Description

1. What I want to do is to remove the space between each item in the ordered list
2. Following is my sample code to do so:
const html =   
> `
    <ul style="line-height: 12px;">
    <li>Test
    <ol>
    <li style="line-height: 12px;margin-bottom:-20px;">Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
    </ol>
    </li>
    <li>Test 2</li>
    </ul>
`
> 

      <HTML source={{html: html}}
                    tagsStyles={{
                      ul: {
                        lineHeight: 0,
                        marginBottom: -20,
                      },
                      ol: {
                        lineHeight: 0,
                        marginBottom: -20,
                      },
                      li: {
                        lineHeight: 0,
                        marginBottom: -20,
                      },
                    }}
    />

3. But there still are some little space between the items of 1), 2) and 3)
![螢幕截圖 2021-02-26 上午11 49 12](https://user-images.githubusercontent.com/61727838/109252683-14081b80-7829-11eb-9907-164fdd849543.png)

**Comment by jsamr** [comment]
@LimanASL This library is somehow limited to what React Native Yoga layout engine can do. It is not a Web engine. If you can produce a satisfactory example with React Native components, it means it is doable ; but I honestly doubt. If you need to have a strictly complying web engine, use `react-native-webview` library instead. Closing now as I don't see how we could possibly work around Yoga limitations, but if you manage to produce a pure React Native example (without this library) were negative margins and zero height lines work as you expect, I'm willing to reopen.
