### ISSUE TITLE
JSON value 'thin' of type NSString cannot be converted to NSNumber

### ISSUE THREAD

**Issue by msageryd** [meliorence/react-native-render-html#470]
I'm using react-native-render-html for rendering email bodies.

When I get the following in the html i get "JSON value 'thin' of type NSString cannot be converted to NSNumber".
```html
    <blockquote type=\"cite\" style=\"border-left-color: grey; border-left-width: thin; border-left-style: solid; margin: 5px 5px;padding-left: 10px;\">
```

I suppose this is just a dev-warning, because it's dismissable. But I also suppose that the "thin" border will be omitted. 

Is this the way the librart shows me that an attribute is not supported?
No biggie, since it renders anyway, but maybe there is room for improvement.

**Comment by jsamr** [comment]
@msageryd I suppose you're using version 5.1.0. This issue is already addressed in v6.x with the separation of CSS parsing in a new package, `@native-html/css-processor`. The v6 is still in alpha. See #430

**Comment by msageryd** [comment]
Thanks!
Thats great news. I'm already thrilled about finding this library. It solves so many problems for me.

Thank you for your work!

**Comment by jsamr** [comment]
@castalonirenz Good catch; that's an edge case since usually percent sizes are translatable in React Native sizes. I'll have a look.

**Comment by jsamr** [comment]
@castalonirenz The issue has been fixed in the latest css-processor release https://github.com/native-html/core/releases/tag/%40native-html/css-processor%401.8.1. You can explicitly install it, or wait for the react-native-render-html@6.0.0-alpha-25 which should be released within a few days.
