### ISSUE TITLE
How to display html in just 1 line

### ISSUE THREAD

**Issue by kelokchan** [meliorence/react-native-render-html#477]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### Libraries

- react-native-render-html: ^11.2.3
- react-native-webview: ^11.2.3

(Describe the expected outcome, and compare it to the observed outcome. You are
encouraged to join screenshots and screencasts, or pictures of the rendering
tree from debugging tools such as flipper)

##### Reproducible Demo
I have a list of html that I need to render in a FlatList. Here's an example of 1 of the html. 
```<div>test</div><div><br></div><ol><li>test1</li><li>test2</li></ol><div><br></div><div><a href="//link" rel="noopener noreferrer" target="_blank">link</a></div><div><br></div><div><strong>bold</strong></div><div><br></div><div><em>italic</em></div>```

I currently have this line of code to render my html:
```
<Html
  style={{ flex: 3 }}
  source={{ html: item.messages }} // item.messages is the html
  defaultTextProps={{
    numberOfLines: 1,
  }}
/>
```

However, the text doesn't seem to be limited and here's how it looks like on the app
<img src="https://user-images.githubusercontent.com/5347725/114814615-14fc0900-9de7-11eb-87c0-7de526737309.png" width="250">

If I limit the container height using ```containerStyle={{
                  height: 40,
                }}```, the html will overflow and overlap the second list item
<img src="https://user-images.githubusercontent.com/5347725/114814672-3b21a900-9de7-11eb-905d-86eacb366ae7.png" width="250">

Any idea how I can fix this issue?

**Comment by jsamr** [comment]
@kelokchan Several options here. But this is not a bug: each `li` creates a new text container, within which the max number of line is 1, which is respected.

- You could add an `overflow: "hidden"` rule on the container style.
- You could [alter the DOM nodes](https://github.com/meliorence/react-native-render-html#altering-content) to filter what you wish to show.
