### ISSUE TITLE
classStyles not being respected

### ISSUE THREAD

**Issue by danhab99** [meliorence/react-native-render-html#480]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Bug Report

[Example code](https://github.com/danhab99/scroll-for-ruqqus/blob/9730bdd705d32fee11c4d1777c11abc12c38771c/components/HtmlMarkdown.tsx#L49)

The `classesStyles` I am providing [here](https://github.com/danhab99/scroll-for-ruqqus/blob/9730bdd705d32fee11c4d1777c11abc12c38771c/components/HtmlMarkdown.tsx#L99) are not being implemented on the components as specified by html downloaded from API. I've already confirmed that the browser is capable of rendering these elements properly

#### Setup

* Refer to [here](https://github.com/danhab99/scroll-for-ruqqus#dev-setup) for setup instructions

##### React Native

```
react-native --version                                                                                                                                                        
5.0.1-alpha.2
```
I'm not sure why but `react-native info` doesn't work for me

##### Libraries

Full list of dependencies [here](https://github.com/danhab99/scroll-for-ruqqus/blob/9730bdd705d32fee11c4d1777c11abc12c38771c/package.json)

- react-native-render-html: "^4.2.4"
- react-native-webview: "^11.0.0"

#### Devices

- Device 1 
  * OS: Android 10
  * Diagnostic: reproduction
  * Environment: development

#### Reproduction

* Have app running
* Create an account with the ruqqus.com provider
* Log in
* Tap the navigate button on the top right (the one that looks like an arrow)
* Type `+scrollforruqus`
* Locate post with id `ad6u` (It will be the last item of the list of muted text words ontop of each post card)

##### Description

`classStyles` are not being respected. Specifically some classes will require certain images to be sized to the width and height of the text. While calculating that is not an issue, the images will not change size. I tried setting their dimensions to exaggerated constants but no change was observed. An easy solution would be to pass `classes` to the custom render handler in the `htmlAttribs` parameter, but they don't get passed. I want to beable to apply all the styles a component needs based on it's classes

##### Reproducible Demo

[Project at broken commit](https://github.com/danhab99/scroll-for-ruqqus/blob/9730bdd705d32fee11c4d1777c11abc12c38771c/)

**Comment by jsamr** [comment]
@danhab99 Versions 4.x of this library are not maintained anymore. Upgrading to v5 will require little to no changes in your codebase. I'm leaving it open while you confirm the issue still exists on v5.x. Please let me know.

**Comment by danhab99** [comment]
Upgraded to `^5.1.0`. No change

![Screenshot_20210428-180856_scrollforruqqus](https://user-images.githubusercontent.com/13894263/116478962-ed785800-a84c-11eb-9a98-6443cdf773be.png)

^ This image as defined by my [HTMLMarkdown.tsx](https://github.com/danhab99/scroll-for-ruqqus/blob/2069234693da4997afdbfed31cd472ae1e9c8bd6/components/HtmlMarkdown.tsx) component should be 1x1 dpi (exaggerated test).

**Comment by danhab99** [comment]
I figured it out. In [this line](https://github.com/danhab99/scroll-for-ruqqus/blob/12a2acfa993c1159387ba51464e42657fd4c369e/components/HtmlMarkdown.tsx#L189) I was accidently destroying the class attribute which caused my problem. I fixed it with lodash.

This took me months to find.

**Comment by jsamr** [comment]
@danhab99 I'm glad you find out, good luck with your ruqqus client!

**Comment by danhab99** [comment]
@jsamr I have one last question to ask. Can we choose for a custom tag renderer to choose whether or not it will be wrapped by a "View" or a "Text" based on the presents of a class?
