### ISSUE TITLE
Square bullet and Alphabetical list not showing

### ISSUE THREAD

**Issue by aneena-thomas** [meliorence/react-native-render-html#481]
### Bug Report
Square bullet and Alphabetical list not showing. Only circle bullet and number list showing

<ul style="list-style-type: square;">
<li>j</li>
<li>hu</li>
<li>mj</li>
</ul>

the above one always render like a circle bullet in react native app

Vesrion: react-native-render-html "^5.1.0"

**Comment by jsamr** [comment]
@aneena-thomas `list-style-type` support has been implemented in the foundry release (#430). As of alpha.24, the following list-style-types are available:

```ts
export type DefaultSupportedListStyleType =
  | 'none'
  | 'disc'
  | 'circle'
  | 'square'
  | 'decimal'
  | 'decimal-leading-zero'
  | 'lower-roman'
  | 'upper-roman'
  | 'lower-greek'
  | 'lower-alpha'
  | 'lower-latin'
  | 'upper-alpha'
  | 'upper-latin'
  | 'disclosure-open'
  | 'disclosure-closed';
```

Thanks to the new `customListStyleSpecs` prop, you can even use directly one of the 47 presets from [@jsamr/counter-style](https://github.com/jsamr/react-native-li/tree/master/packages/counter-style#readme) which allows declaration of [@counter-style CSS at-rule](https://drafts.csswg.org/css-counter-styles-3/#the-counter-style-rule) in React Native, or create your own marker renderer. **Example, support "hebrew" list-style-type**:

```jsx
import RenderHTML from 'react-native-render-html';
import hebrew from '@jsamr/counter-style/presets/hebrew';

const customListStyleSpecs = {
  hebrew: {
    type: 'textual',
    counterStyleRenderer: hebrew
  }
};

//
<RenderHTML customListStyleSpecs={customListStyleSpecs} />
```

**Comment by aneena-thomas** [comment]
Thank you @jsamr  for the reply, so version 5.1.0 has no feature like this right. We need to wait for 6.0.0

**Comment by jsamr** [comment]
@aneena-thomas You can already try it out, see #430 for instructions. The API won't evolve much and we're very close to beta-release with a frozen API. The only thing that might yet change are the `alter*` props to tamper the DOM. So if you're not using them, you shouldn't fear trying the alpha right now. I'll start the beta release when a minimal version of the documentation website will be ready. During the beta phase, I'll try to reach a 90%+ test coverage (currently 65%+). The internal logic to transform HTML into pre-rendered nodes and CSS processing [have already a 100% test coverage](https://github.com/native-html/core). What I mean is this is solid, tested code, with a huge amount of bug fixes from v5! The only pitfall is its current lack of documentation... you can always reach me on our discord channel if you have any question!

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).
