### ISSUE TITLE
Text decoration style is not getting decoded

### ISSUE THREAD

**Issue by Tanuja0049** [meliorence/react-native-render-html#482]
### Oath

I swear that I have completed these tasks before submitting:

- [ ] I have read the help guide here: https://git.io/JJ0y3
- [ ] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [ ] I have read the documentation here: https://git.io/JJcAl 

------------

Hi,

We are using this library to decode the html content in react native code. We have one issue where we are getting text decoration style on some tags and the library is not decoding this.

Example Tag:
&lt;span style="text-decoration:line-through;">text of the printing &lt;/span>

This text is expected to be shown with strikethrough style, but it is not applying the style. 

Please let us know if this feature is already available or is considered for any upcoming updates?

**Comment by Tanuja0049** [comment]
Hi,

below are more details for issue:

Platform: Android and IOS
Versions used: 
     "react-native-render-html": "^5.1.0"
     "react-native": "0.63.2",

Please let me know if more information is needed for this issue.

Thank you

**Comment by Tanuja0049** [comment]
Thank you. I will check this. We are actually making use of custom renderers so I will have to check functionality for those as well.

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).
