### ISSUE TITLE
[Question] How renderers: img works?

### ISSUE THREAD

**Issue by jeancatarina** [meliorence/react-native-render-html#484]
Hello, i am trying to download all images, after that show my HTML with the local images that i previous downloaded. Create a regex to find all the possibilities that a image can be showed its hard. But the renderer works perfectly and finds all image that i need. My question is, how i can find all images, like the renderer, without using the renderer? I need to download the images before render my html, so i cant use the renderer for this.

```
const defaultRenderer = {
    renderers: {
      img: (
        htmlAttribs: any,
        children: any,
        convertedCSSStyles: any,
        passProps: any,
      ) => {
        return (
          <Image
            key={passProps.key}
            style={styles.image}
            source={{uri: `${htmlAttribs.src}`}}
          />
        );
      },
    },
  };
```

**Comment by jsamr** [comment]
@jeancatarina If I understood you well, you'd like to query images in the DOM before rendering happens, right? If that's the case, the next Foundry alpha (.25, which should be the last before beta release cycle) will address that requirement ;-) I'll post an update here on how to achieve this when it is available.

**Comment by jsamr** [comment]
This is how it will look like in pre-release 6.0.0-alpha.25 (**not released yet**). The use case is covered thanks to 3 new features:

- `RenderHTMLSource` component which, in addition to previously supported uri and html fields, allows to render a DOM object from `htmlparser2`.
- `TRenderEngineProvider` and `useAmbientTRenderEngine` which allows to share an instance of the transient render engine across your App.
- `TRenderEngine.parseDocument` new method to parse HTML into a DOM representation.

```jsx
import React, { useState, useEffect, useMemo } from 'react';
import {
  TRenderEngineProvider,
  RenderHTMLConfigProvider,
  RenderHTMLSource,
  useAmbientTRenderEngine
} from 'react-native-render-html';
import { findAll } from 'domutils';

function isImgElement(node) {
  return node.name === 'img';
}

function RenderSource({ html }) {
  const [isDomReady, setIsDomReady] = useState(false);
  // Let's use the TRE provided from the root of our app
  // via TRenderEngineProvider to build the DOM
  const engine = useAmbientTRenderEngine();
  const dom = useMemo(() => engine.parseDocument(html), [html, engine]);
  // Use effect to inspect the DOM
  useEffect(function inspectDom(){
    // Do any pre-rendering logic here
    const images = findAll(isImgElement, dom, true);
    // Do stuff with images such as preloading
    // ...
    // When preloading is done, set isDomReady to true!
    setIsDomReady(true);
  },[dom]);
  return isDomReady ?
    <RenderHTMLSource source={{ dom }} />
    : null;
}

const html = `
hello world!
<img src='https://img.io/001.jpg' />
`

export default function App() {
  return (
    <TRenderEngineProvider>
      <RenderHTMLConfigProvider>
        <RenderSource html={html} />
      <RenderHTMLConfigProvider>
    </TRenderEngineProvider>
  );
}
```

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).

**Comment by Slapbox** [comment]
@jsamr are there some docs we should look at for what gets passed to `RenderHTMLConfigProvider`, if anything? [The commit notes](https://github.com/meliorence/react-native-render-html/commit/7d50e72bb3dcf585e96bd80d475f9c9170be427b) mention to see the TypeScript defs for `TRenderEngineProvider`.

I found the same for the `RenderHTMLConfigProvider` [here](https://github.com/meliorence/react-native-render-html/blob/master/apps/benchmarking/App.js) - but I'm wondering if this is somewhere in the docs already or if it's not added yet?

Thanks again for your great work on RNRH!
