### ISSUE TITLE
 [6.x] 🚀 Announcing Foundry Beta Release

### ISSUE THREAD

**Issue by jsamr** [meliorence/react-native-render-html#489]
## Check-out [**our blog announcement**](https://meliorence.github.io/react-native-render-html/blog/2021/06/07/foundry-announcement).

[![](https://meliorence.github.io/react-native-render-html/img/foundry-announcement.png)](https://meliorence.github.io/react-native-render-html/blog/2021/06/07/foundry-announcement)

## Comment in this thread if you face any issue.

**Comment by Slapbox** [comment]
@jsamr are there some docs we should look at for what gets passed to RenderHTMLConfigProvider, if anything? The commit notes mention to see the TypeScript defs for TRenderEngineProvider.

I found the same for the RenderHTMLConfigProvider here - but I'm wondering if this is somewhere in the docs already or if it's not added yet?

Thanks again for your great work on RNRH!

**Comment by jsamr** [comment]
@Slapbox Hi! Thanks for the feedback. Props for `RenderHTMLConfigProvider`:  https://meliorence.github.io/react-native-render-html/api/renderhtmlconfig
For `TRenderEngineProvider`: https://meliorence.github.io/react-native-render-html/api/trenderengineconfig
[There is a quick guide in the docs](https://meliorence.github.io/react-native-render-html/docs/flow/rendering).
