### ISSUE TITLE
Tagsstyle doesnt work

### ISSUE THREAD

**Issue by tcagkansokmen** [meliorence/react-native-render-html#494]
I'm using like that;

  
```
 tagsStyles={{ 
              h1: [styles.htmlStyle, {color: colors.text, fontSize: 22, fontWeight: '700', lineHeight: 32}],
              h2: [styles.htmlStyle, {color: colors.text, fontSize: 20, fontWeight: '700', lineHeight: 30}],
              h3: [styles.htmlStyle, {color: colors.text, fontSize: 18, fontWeight: '700', lineHeight: 28}],
              h4: [styles.htmlStyle, {color: colors.text, fontSize: 16, fontWeight: '700', lineHeight: 26}],
              h5: [styles.htmlStyle, {color: colors.text, fontSize: 14, fontWeight: '700', lineHeight: 24}],
              p: [styles.htmlStyle, {color: colors.text, fontSize: 12, lineHeight: 24}],
              ul: [styles.htmlStyle, {color: colors.text, fontSize: 12, lineHeight: 24, listStyle: 'none'}],
              li: [styles.htmlStyle, {color: colors.text, fontSize: 12, lineHeight: 24, listStyle: 'none'}],
              em: [styles.htmlStyle, {color: colors.text}],
              strong: [styles.htmlStyle, {color: colors.text, fontWeight: '700'}],
            }}
```

But it doesnt work.
What's wrong with it?

I read all documentation and couldn see, how to assign css styles for html elements

**Comment by jsamr** [comment]
@tcagkansokmen `tagsStyles`must be a record of objects, not arrays! Quoting from the docs:

> **Do NOT** use the StyleSheet API to create those styles.

See https://meliorence.github.io/react-native-render-html/api/renderhtmlprops#tagsstyles

The warning is also repeating in the **styles** guide; but perhaps the docs are missing something. If you find that you read something misleading, please tell me. I could also enforce the type a bit more strictly at runtime.

**Comment by jsamr** [comment]
you can use |`StyleSheet.flatten`](https://reactnative.dev/docs/stylesheet#flatten) to work around the issue:
```js
const tagsStyles = {
  h1: StyleSheet.flatten([
    styles.htmlStyle,
    { color: colors.text, fontSize: 22, fontWeight: "700", lineHeight: 32 },
  ]),
  // ...
};
```

**Comment by jsamr** [comment]
Closing now, but feel free to comment if you still have questions.
