### ISSUE TITLE
`text-decoration` on `a` tags does not take effect

### ISSUE THREAD

**Issue by aprilmintacpineda** [meliorence/react-native-render-html#495]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### React Native

```
info Fetching system and libraries information...
System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 1.12 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.10.0 - ~/.nvm/versions/node/v15.10.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.3 - ~/.nvm/versions/node/v15.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 24, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

##### Libraries

- react-native-render-html: ^5.1.1
- react-native-webview: ^11.6.4

#### Devices

- Device 1: Samsung galaxy A01 (real device)
  * OS: 10
  * Diagnostic: reproduction
  * Environment: development
- Device 2: iPhone 6s (real device)
  * OS: 12.2
  * Diagnostic: reproduction
  * Environment: development

#### Reproduction

see below.

##### Description

Use the following code to replicate:

```jsx
<HTML
  source={{ html: '<a href="google.com">testing</a>' }}
  alterNode={alterNode}
/>
```

here's the `alterNode` function:

```js
function alterNode(node) {
  if (node.name === 'a') {
    node.attribs = {
      ...node.attribs,
      style: 'color: orange; text-decoration: none;'
    };

    return node;
  }
}
```

The `color` takes effect but the `text-decoration` does not take effect. I have tried other `text-decoration` but none of them took effect. https://www.w3schools.com/cssref/pr_text_text-decoration.asp All I want to do here is remove `text-decoration` from anchor tags.

##### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant
source code. When deemed appropriate, provide instructions to reproduce the
issue.)

(If you plan to provide a Regression Test PR, just leave a line written
*Planned Regression Test* and link it here when it's ready. We will be happy to
provide you help with crafting the test on our Discord #contributing channel.)

**Comment by aprilmintacpineda** [comment]
Okay, I have tested all sorts of combinations and none of them worked.

```js
function alterNode(node) {
  if (node.name === 'p') {
    node.attribs = {
      ...node.attribs,
      style: `color: ${theme.colors.primary}; text-decoration: underline;`
    };

    return node;
  }
}
```

RESULT: DID NOT WORK.

```jsx
<HTML
  source={{ html: '<p style="text-decoration: underline;">test</p>' }}
  alterNode={alterNode}
/>
```

RESULT: DID NOT WORK.

Seems nothing works when it comes to `text-decoration`

**Comment by jsamr** [comment]
`text-decoration` is a shorthand CSS property for `text-decoration-line`, `text-decoration-color`, `text-decoration-style`. The longhand properties will work in V5. Generic shorthands properties support has landed on V6. So the easiest workaround is to use those longhands.

I won't implement a shorthand support in V5 but I'm open to PRs (make sure the PR is against dev/5.x).

**Comment by aprilmintacpineda** [comment]
> `text-decoration` is a shorthand CSS property for `text-decoration-line`, `text-decoration-color`, `text-decoration-style`. The longhand properties will work in V5. Generic shorthands properties support has landed on V6. So the easiest workaround is to use those longhands.
> 
> I won't implement a shorthand support in V5 but I'm open to PRs (make sure the PR is against dev/5.x).

I tried `text-decoration-line: none;` but still did not work. I switched to `@next` instead.

**Comment by jsamr** [comment]
@aprilmintacpineda You could also have tried `tagsStyles` and target `a` elements that way... anyway, going to close now since this "bug" is affecting an older version of this library.
