### ISSUE TITLE
Examples without complex cases, such as internal styles, inline styles cannot meet the needs

### ISSUE THREAD

**Issue by fungmo** [meliorence/react-native-render-html#498]
![image](https://user-images.githubusercontent.com/16655229/123353981-4b979200-d595-11eb-9f7c-59b3660fca88.png)

**Comment by jsamr** [comment]
@fungmo Sorry, what is the feature request?

**Comment by jsamr** [comment]
If you mean support the `<style>` tag, there is already a feature request open, see #381
Closing now. I suggest you [don't ignore our template and guidelines](https://github.com/meliorence/react-native-render-html/blob/master/CONTRIBUTING.adoc#tickets) and post your question on our Discord channel next time!
