### ISSUE TITLE
table scroll

### ISSUE THREAD

**Issue by amansaxenalapa11** [meliorence/react-native-render-html#500]
table scroll is not smooth if i scroll table horizontally then it stuck and not as smooth as in vertical slide

**Comment by jsamr** [comment]
Hi @amansaxenalapa11! You need to follow [our guidelines](https://github.com/meliorence/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug) if you want us to be able to help you. Our policies detail that issues missing templates (especially when no reproduction is provided) will be closed without notice, and thus I will have to close this one. But feel free to resubmit a new issue complying with our template.
