### ISSUE TITLE
Can it support both inline images  and no inline images  in the same html?

### ISSUE THREAD

**Issue by nangongmoyan** [meliorence/react-native-render-html#501]
I want to display the icon in the middle of the text, for example below:
![image](https://user-images.githubusercontent.com/48037565/123587911-8f9ac900-d819-11eb-9282-1c50b675cb0b.png)
my code:
```
<HTML
           html={`<p><p>An inline SVG image is embedded to present the Italy flag
<img src="https://fomoyolo-dev-assets.s3.amazonaws.com/image-gallery/c4ea7600-9acb-11ea-a7d0-9bf50f73b3c4.jpg" style="height:px; width:10px" />
in a paragraph of text...
</p><img src="https://fomoyolo-dev-assets.s3.amazonaws.com/image-gallery/c4ea7600-9acb-11ea-a7d0-9bf50f73b3c4.jpg" style="height:px; width:10px" /></p>`}/>
```
my question: when i need inline images, i set my code:
```
 const customHTMLElementModels = {
    img: defaultHTMLElementModels.img.extend({
      contentModel: HTMLContentModel.mixed,
    }),
}
```
but i set p lingHeight value, second images will cover prev text

**Comment by jsamr** [comment]
@nangongmoyan I understand the need here. This is currently a limitation of the Transient Render Engine (quoting the docs):

> You cannot set the contentModel dynamically. This is currently a limitation of the ​TRE. 

What will likely happen in a future major is support for `display: inline` and `display: block`. The content model will then be derived from this style which would address the feature you requested.

**Comment by jsamr** [comment]
I've just added this feature to our new Feature Requests Tracker (canny) : [Support "display: inline" and "display: block" for dynamic content models](https://native-html.canny.io/features/p/support-display-inline-and-display-block-for-dynamic-content-models). Closing now as feature requests should now-on be submitted in our canny.
