### ISSUE TITLE
List item(OL/UL) text align center is not working as expected.

### ISSUE THREAD

**Issue by shameersn** [meliorence/react-native-render-html#506]
### Oath

I swear that I have completed these tasks before submitting:

- [X] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [X] I have read the documentation here: https://meliorence.github.io/react-native-render-html/
- [X] I have confirmed that this bug has not been reported yet

### Bug Report

- While applying text align center or right to `ol,ul or li` elements the actual text is aligned but not the bullet points or numbers
- In CSS there is an option `list-style-position: inside;`, but unable to provide this style to ul/ol as its not a valid property in react native
- Was able to reproduce the same issue in iOS and Android

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-15 at 15 01 21](https://user-images.githubusercontent.com/10277908/125765705-8ccaa03e-14c2-47bb-bd79-976cb2a352d4.png)

#### Setup

```
const source = `<ul>
  <li>ONe</li>
  <li>abc</li>
  <li>there</li>
</ul>
<ol>
  <li>One</li>
  <li>Tow</li>
  <li>there</li>
</ol>`;

<HTML
     tagsStyles={{
            li: {
              textAlign: 'center',
            },
      }}
      source={{html: source}}
      baseFontStyle={{fontSize:28}}
/>
 ```

##### React Native
"react-native": "0.64.2",
"react-native-render-html": "^5.1.1",

```
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 149.82 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.1.0/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

##### RNRH

- react-native-render-html: "^5.1.1"
##### Description

1.  Provide html with UL or OL elements
2. Apply textAlign center
3. Render the html
4. The bullet points or the number in the ordered list are left aligned while the actual text is center aligned
5.  I tried with `listsPrefixesRenderers` and new beta version 6. unable to resolve

**Comment by lyseiha** [comment]
+1

**Comment by jsamr** [comment]
@shameersn The thing is, there are no pseudo elements in React Native. The markers are rendered inside `Views`. In the web, the `::marker` pseudo-element displaying list prefixes will honor `text-align: center`, so I will not attempt to implement a hacky workaround here. However, you should be able to have a similar outcome by aligning `ol` to center:

``` js
const tagsStyles = {
  ul: {
    alignSelf: 'center',
  },
  ol: {
    alignSelf: 'center',
  },
};
```
I tested on **v6** (see screenshot), not on v5, but I would expect it work there too.

![image](https://user-images.githubusercontent.com/3646758/126039148-e11068b3-2e95-403e-a579-75d861337aa4.png)

**Comment by shameersn** [comment]
@jsamr Thanks for the help and update.
But seems to now the content is missing. Please see the attachment.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-17 at 20 30 39](https://user-images.githubusercontent.com/10277908/126041140-c20e474e-3e5d-42c3-a533-01017d941460.png)

**Comment by jsamr** [comment]
@jsamr Have you tested with v6?

**Comment by shameersn** [comment]
Will test in v6, thanks

**Comment by shameersn** [comment]
@jsamr Thanks for this wonderful library and the support 🙌. 
Works perfectly in "react-native-render-html": "^6.0.0-beta.8".

**Comment by jsamr** [comment]
@shameersn I'm glad that worked out for you! If you'd like to help us, [you could consider writing a review on Openbase :wink: ](https://openbase.com/js/react-native-render-html)
