### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'domelementtype_1.ElementType.Tag')]

### ISSUE THREAD

**Issue by Thanhal-P-A** [meliorence/react-native-render-html#507]
By just importing the package
 **import RenderHtml from 'react-native-render-html'**
it shows following error 

**[Error: Requiring module "node_modules\react-native-render-html\src\index.ts", which threw an exception: TypeError: undefined is not an object (evaluating 'domelementtype_1.ElementType.Tag')]**

![MicrosoftTeams-image](https://user-images.githubusercontent.com/42827490/126138492-6aaa7d73-332f-4339-b997-b834f759b62c.png)

**Comment by jsamr** [comment]
Hi @Thanhal-P-A! Please don't take this personally, but we require [issues to follow a set of guidelines to be accepted](https://github.com/meliorence/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug). Without any reproduction, we are unable to investigate your issue. Closing now, you're welcome to resubmit an issue following our template and including a reproduction. Thank you!
