### ISSUE TITLE
How to style list bullets in v6?

### ISSUE THREAD

**Issue by SergiOnGit** [meliorence/react-native-render-html#509]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://meliorence.github.io/react-native-render-html/
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Bug Report
Before updating to v6 I was using this setup for styling bullet, but now from docs I don't understand how to achieve the same
```
listsPrefixesRenderers={{
                        ul: () => {
                            return <View style={{
                                marginRight: 10,
                                width: 10, 
                                height: 10,
                                marginTop: 12,
                                borderRadius: 12,
                                backgroundColor: 'red',
                            }} />
                        },
                    }}
```

Can anyone help?

**Comment by jsamr** [comment]
@SergiOnGit Hi! It's true that the API has been totally reworked for list prefixes. You can now take advantage of `renderersProps.ul` like below:

```jsx
import * as React from 'react';
import {ScrollView, StyleSheet, useWindowDimensions} from 'react-native';
import HTML from 'react-native-render-html';

const html = '<ul><li>Foo</li><li>Bar</li></ul>';

const renderersProps = {
  ul: {
    markerBoxStyle: {
      paddingRight: 10,
    },
    markerTextStyle: {
      color: 'red',
    },
  },
};

export default function App() {
  const {width: contentWidth} = useWindowDimensions();
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <HTML
        renderersProps={renderersProps}
        defaultTextProps={{selectable: true}}
        contentWidth={contentWidth}
        source={{html}}
      />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: 'white',
  },
});
```
`textMarkerStyle` refers to the textual component (even if it's using a `View`, it will adapt to `color`, `fontSize`... etc) while `textBoxStyle` refers to the container. Refrain from using any margins in the later, as that could break some features. Checkout the full [list of customizations available in `renderersProps.ul` here](https://meliorence.github.io/react-native-render-html/api/listelementconfig).
However, there is no way yet to define your own marker (alias for prefix) component.

**Comment by SergiOnGit** [comment]
It works. Thank you! Should be great if you improve docs with such examples.

**Comment by jsamr** [comment]
Yes good point! Thanks.

**Comment by Slapbox** [comment]
@jsamr thanks for your hard work on this project! 

Is there a plan for a way to pass a custom character so we can use a dash (- or —) as our list marker for both `<ul />` _and_ `<ol />`? 

We've ported a lot of our changes over to 6.x today, but my heart sank a bit when I saw there's nothing we can do to replicate, or even emulate, the styles we were using in 5.x. I love the changes overall; a lot of things are just way smoother, but is support for custom text marker characters planned, I hope?

**Comment by jsamr** [comment]
> Is there a plan for a way to pass a custom character so we can use a dash (- or —) as our list marker for both `<ul />` and `<ol />`?

@Slapbox You already can, see https://meliorence.github.io/react-native-render-html/docs/content/lists#defining-and-customizing-markers-pseudo-elements You'll need to create [a cyclic counter renderer](https://github.com/jsamr/react-native-li/blob/master/packages/counter-style/docs/counter-style.counterstylestatic.md) with one character.
