### ISSUE TITLE
Anonymous tag text color

### ISSUE THREAD

**Issue by neneji** [meliorence/react-native-render-html#515]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

cannot change color of a anonymous tag text.
I'm trying to render text comes from a database, but its not always have a tag such as `p` or `span`, and some time we receive a simple text. 
I tried to use the `baseStyle` to give it a `color: "white"` but it did work. how could i change the color of text in this case? cannot find any usage case like this.

### React Native Information

```sh
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 422.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/npm-global/bin/yarn
    npm: 7.16.0 - ~/npm-global/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Arctic Fox 2020.3.1 Arctic Fox 2020.3.1
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### RNRH Version

^6.0.5

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

```
<HTML
      baseStyle={{
        color: 'white',
        backgroundColor: 'red',
      }}
      // renderers={{
      //   p: (htmlAttribs, children, convertedCSSStyles, passProps) => (
      //     <Paragraph>{children}</Paragraph>
      //   ),
      //   li: (htmlAttribs, children, convertedCSSStyles, passProps) => (
      //     <Text>{children}</Text>
      //   ),
      // }}
      renders={{
        p: ({
          tnode,
          onPress,
          propsFromParent,
          sharedProps,
          style,
          textProps,
          type,
          viewProps,
          InternalRenderer,
          TDefaultRenderer,
        }) => {
          return <Paragraph>{tnode.children}</Paragraph>;
        },
      }}
      source={{html: htmlText}}
      contentWidth={1}
      tagsStyles={tagsStyles}
    />
```

**Comment by jsamr** [comment]
@neneji You need to provide an HTML snippet in your reproduction, otherwise we are unable to ... reproduce!
