### ISSUE TITLE
On iOS, the underline color of <a> is different from the text

### ISSUE THREAD

**Issue by 1280103995** [meliorence/react-native-render-html#517]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

The underline color of the <a> tag should be the same as the text, which works as expected on Android. On iOS, it shows blue color.

<img src="https://user-images.githubusercontent.com/17424486/130552543-edd43d0c-7564-40f8-9bd5-abbffe099e27.jpg" width="30%" height="30%"/>

<img src="https://user-images.githubusercontent.com/17424486/130552553-93e8ca48-6628-4b68-b7e1-e7544b089e2c.PNG" width="30%" height="30%"/>

### React Native Information

```sh
System:
    OS: macOS 11.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 347.64 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.4.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 7.0.15 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

### RNRH Version

"react-native-render-html": "^6.0.5",

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

```
import React from 'react';
import {useWindowDimensions, View} from 'react-native';
import RenderHtml from 'react-native-render-html';

export function App2() {
  const { width } = useWindowDimensions();
  return(
    <View style={{flex:1, justifyContent:'center', alignItems:'center'}}>
    <RenderHtml
      contentWidth={width}
      source={{ html: '<p>This is a test <a href="https://www.github.com">message</a></p>' }}
      tagsStyles={styles}
    />
    </View>
  )
}

const styles = {
  p: {
    fontSize: 50,
    color: 'black'
  },
  a: {
    color: 'red',
    textDecorationLine: 'underline',
  }
}
```

### Additional Notes

Remove the ```href ```attribute and it works fine

**Comment by thame** [comment]
This can be modified on iOS by setting `textDecorationColor` to the desired color.

**Comment by 1280103995** [comment]
> This can be modified on iOS by setting `textDecorationColor` to the desired color.

Perfect
