### ISSUE TITLE
Unordered List not nesting properly

### ISSUE THREAD

**Issue by mineminemine** [meliorence/react-native-render-html#522]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

I believe this is a similar issue to this one here #173 but the issue I'm posting now is the other way around.

Code:
```
<ul>
  <li>Tea</li>
  <li>Coffee</li>
  <ol>
    <li>Dog</li>
    <li>Cat</li>
  </ol>
</ul>
```

Expected result:
<ul>
  <li>Tea</li>
  <li>Coffee</li>
  <ol>
    <li>Dog</li>
    <li>Cat</li>
  </ol>
</ul>

Actual result:
<ul>
  <li>Tea</li>
  <li>Coffee</li>
  <li>
    <ol>
      <li>Dog</li>
      <li>Cat</li>
  </ol>
  </li>
</ul>

### React Native Information

```sh
Expo CLI 4.11.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - C:\Users\Ryan\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: ^17.0.2 => 17.0.2
      react-dom: ^17.0.2 => 17.0.2
      react-native: ^0.64.2 => 0.64.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### RNRH Version

6.1.0

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/Kgn-_Ny45

**Comment by mineminemine** [comment]
```
<ol>
  <li>Tea</li>
  <li>Coffee</li>
  <ul>
    <li>Dog</li>
    <li>Cat</li>
  </ul>
</ol>
```

Now that I look at it again, having the ol and ul the other way around would also give unwanted result.
https://snack.expo.dev/qDwgiy5Ti

**Comment by jsamr** [comment]
@mineminemine Did you try to validate your HTML snippet [against W3C validator](https://validator.w3.org/nu/#textarea) such as recommended in our guidelines? The test fails because you can only have `li` as children of `ul` and `ol`:

![image](https://user-images.githubusercontent.com/3646758/134143063-6aa1a866-f2f5-4f4f-a683-d94b0174a5e9.png)

**Comment by jsamr** [comment]
@mineminemine Since it is non-compliant, the parser library (htmlparser2) attempts a fix by wrapping `ol` with `li` element!

**Comment by mineminemine** [comment]
@jsamr Oh my god, truly sorry for this. This just goes to show that I've been doing nested list wrongly all these years.. I'll just close this issue since mistake was on my end. Sorry and thank you for your time.

**Comment by jsamr** [comment]
@mineminemine no worries, we all make mistakes :-) Browsers are kind of unhelpful to learn those things because of their laxness...

**Comment by federicoeventifica** [comment]
Hello, I'm facing the same problem, and after reading this thread I found out that the issue is the malformed html and not the react-native-render-html.

Do you know any library or function that transforms an html with this format:
```
<ol>
  <li>Tea</li>
  <li>Coffee</li>
  <ul>
    <li>Dog</li>
    <li>Cat</li>
  </ul>
</ol>
```

to this (the right way):
```
<ol>
  <li>Tea</li>
  <li>Coffee
  <ul>
    <li>Dog</li>
    <li>Cat</li>
  </ul>
  </li>
</ol>
```

Thank you,
Federico

**Comment by jsamr** [comment]
@federicoeventifica If you want to do this transformation front-wise, you could use DOM tempering features available in this library, see this documentation page: https://meliorence.github.io/react-native-render-html/docs/guides/dom-tampering

**Comment by ashwanihundwani1986** [comment]
How to change the bullet icon
![Simulator Screen Shot - iPhone 13 - 2022-07-13 at 21 44 48](https://user-images.githubusercontent.com/105865354/178807394-025d5585-4a21-4921-9178-d48bef9b25ae.png)
 but keep the content same as with new CustomRenderer(V6) we do not get the React DOM in CustomRendererProps the way we used to get it (V5).

**Comment by Slapbox** [comment]
I don't understand if this is still an issue? Is the extra bullet caused by the custom renderer? Because we don't see that with the default renderers with identically nested HTML lists.

**Comment by mgutbezahl** [comment]
I wrote this solution to "clean up" the nested lists, maybe need more styling on the final result, but it works

Funtion:

```
sanitizeListHTML: (element) => {
    if (['ol', 'ul'].includes(element.tagName)) {
      const { children } = element;
      for (let i = 0; i < children.length; i++) {
        const child = children[i];
        let nextSibling = children[i + 1];
        while (nextSibling && ['ol', 'ul'].includes(nextSibling.tagName)) {
          child.children.push(nextSibling);
          children.splice(i + 1, 1); // Remove the nested list from its original position
          nextSibling = children[i + 1];
        }
      }
    }
  },
```

And usit like this on the component:

```
<RenderHTML
          contentWidth={width}
          source={{ html: props.text?.trim() }}
          tagsStyles={tagsStyles}
          domVisitors={{ onElement: helpers.sanitizeListHTML }}
        />
```

![Captura de pantalla 2024-06-19 a las 15 40 14 p  m](https://github.com/meliorence/react-native-render-html/assets/37155422/86c6c2af-a43f-49ed-a779-380bb2bfe4bb)

**Comment by Nantris** [comment]
That's very nifty! Thanks for sharing!

Maybe I'm reading it wrong, but my interpretation is that you're un-nesting the lists, but then I'm confused how the indentation is being handled? The end result looks great though!

**Comment by mgutbezahl** [comment]
> That's very nifty! Thanks for sharing!
> 
> Maybe I'm reading it wrong, but my interpretation is that you're un-nesting the lists, but then I'm confused how the indentation is being handled? The end result looks great though!

I'm using this https://github.com/meliorence/react-native-render-html/issues/522#issuecomment-946825772 as a solution, making the "correct" format for the HTML to be render.

**Comment by Nantris** [comment]
Very cool! Thanks for taking the time to explain!
