### ISSUE TITLE
how to render mathjax at some point by using custom rendering 

### ISSUE THREAD

**Issue by amansaxenalapa11** [meliorence/react-native-render-html#532]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

i want to custom render mathjax when a specific class is present in the code is it possible or any example there for this

### React Native Information

```sh
https://snack.expo.dev/@amansaxena11/mathjax-equation-in-html
```

### RNRH Version

 "react-native-render-html": "^5.1.1",

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/@amansaxena11/mathjax-equation-in-html

### Additional Notes

i have use Inserting Element but its not working for me

**Comment by jsamr** [comment]
@amansaxenalapa11 Hi, and thanks for this report! Unfortunately, the issue tracker is no fit for assistance. Please post to Stackoverflow or our Discord for help. A few notes though:

- You are using `domVisitors` with version 5 of this library, which does not support this prop.
- You are not using `onElement` as expected. Check for examples in the official website (search for "dom tampering").
- [We have a guide on custom rendering](https://meliorence.github.io/react-native-render-html/docs/guides/custom-renderers). I suggest you register a custom component renderer and renders conditionally your special renderer
```jsx
if (tnode.hasClas("mathjaxclass") {
  return /* My special component */
}
```
Good luck!
