### ISSUE TITLE
i want to render mathjax whenever a "div" comes with class "mathjax" 

### ISSUE THREAD

**Issue by amansaxenalapa11** [meliorence/react-native-render-html#536]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

i want to render mathjax whenever a "div" comes with class "mathjax" i am using rnrh version "^5.1.1" i have applied Custom HTML tags but in props it give me whole data i want only data which is inside the perticular div tag is there any other way to render mathjax at specific points . if yes give example

### React Native Information

```sh
"react-native": "0.63.4",
```

### RNRH Version

"react-native-render-html": "^5.1.1"

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/@amansaxena11/mathjax

### Additional Notes

renderers: {
  table,
  div : (child ,htmlAttribs, passProps , data , domNode)  => {
    console.log(data.source.html, 'data')
  return(<View >
    <MathJax html={data.source.html}  />
    </View>)}
  },

**Comment by jsamr** [comment]
Hi @amansaxenalapa11, and thanks for your report! The issue tracker is meant for bug reports, not assistance. For assistance, post to StackOverflow or to our Discord such as suggested [in our help guide](https://github.com/meliorence/react-native-render-html/blob/master/HELP.adoc). Thank you!
