### ISSUE TITLE
The "input" tag is a valid HTML element but is not handled by this library.

### ISSUE THREAD

**Issue by VitaliyGaliy** [meliorence/react-native-render-html#538]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Can not use an input HTML element.

### React Native Information

```sh
"expo": "~43.0.0",
 "react-native": "0.64.2",
```

### RNRH Version

0.64.2

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

`
const source = {
  html: <p style='text-align:center;'>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
            <input />Quo minima quis accusamus rerum dolorum! 
        </p>
};

const customHTMLElementModels = {
  'input': HTMLElementModel.fromCustomModel({
    tagName: 'input',
    mixedUAStyles: {
      width: 50,
      height: 10,
      backgroundColor: 'blue'
    },
    contentModel: HTMLContentModel.block
  }),
};

const App = () => {

  const { width } = useWindowDimensions();
  return (
    <RenderHtml
      contentWidth={width}
      source={source}
      customHTMLElementModels={customHTMLElementModels}
  />
  );
};
`

**Comment by jsamr** [comment]
@VitaliyGaliy Thanks for the report! The default content model for input is "none", because interactive elements are not handled by default. You need to provide [an element model with block content model](https://meliorence.github.io/react-native-render-html/docs/guides/custom-renderers#model-based-custom-rendering); I agree this could be documented in the FAQ!
