### ISSUE TITLE
Bold tag not rendering correctly

### ISSUE THREAD

**Issue by faisal-vf** [meliorence/react-native-render-html#539]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Recently migrated to `6.3.0` from `5.1.0` and noticed that bold tag is no longer working. e.g.

```
const source = {
  html: `
<p style='text-align:center;'>
  <b>Hello World!</b>
</p>`
};
```
 I resolved this issue by using `tagsStyles`

```
tagsStyles = {{ b: { fontWeight: "bold" } }}
```

This is tested on both iOS (15.0) and android (11) with react native 0.64.2

### React Native Information

```sh
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 128.71 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.2.1 - ~/.nvm/versions/node/v15.2.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.24.2 - ~/.nvm/versions/node/v15.2.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 26, 28, 29, 30, 31
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### RNRH Version

6.3.0

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

```
const source = {
  html: `
<p style='text-align:center;'>
  <b>Hello World!</b>
</p>`
};
```

**Comment by jsamr** [comment]
@faisal-vf thank you so much for this fair report! That will be fixed soon.
