### ISSUE TITLE
How to  set a preload img before iframe show

### ISSUE THREAD

**Issue by tigerjiang** [meliorence/react-native-render-html#540]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

When I use iframe-plugin to load a video, there is a long time show white blank before the video show. So I cant add a loading img before the video shown. How can I do it. I found the method onHTMLLoaded, but it doesn't effect.
` renderVideo(title,video, navigation ) {
    const iframeContent = ` <iframe src=${video} width="1427" height="800" frameborder="0"  allow="autoplay" allowfullscreen></iframe>`
    return <View style={styles.videoContainer}>
        <View style={styles.videoContainer}>

          <RenderHtml
            WebView={WebView}
            contentWidth={Dimensions.get('window').width}
            style={styles.videoContainer}
            source={{ html: iframeContent }}
            renderers={renderers}
            onHTMLLoaded={(html)=>{
              console.log("onHTMLLoaded "+html)
            }}
            customHTMLElementModels={customHTMLElementModels}
          />
        </View>
        <View style={styles.absoluteTitle}>
          <LearnVideoDetailTitle
            navigation={navigation}
            title={title}
            goBack={() => navigation.goBack()}
          />
        </View>
    </View>
  }`

### React Native Information

```sh
"react": "16.13.1",
    "react-native": "^0.63.4",
```

### RNRH Version

    "react-native-render-html": "^6.1.0",

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

NO

**Comment by jsamr** [comment]
@tigerjiang Thanks for your feedback. Please note that this tracker is not suited to ask for help, but I will give you a hint on how to achieve what you're looking for. [`onHTMLLoaded` as documented](https://meliorence.github.io/react-native-render-html/api/renderhtmlsourceprops#onhtmlloaded) fires when HTML is ready to render in the `RenderHTML` component. It has nothing to do with the iframe renderer.

You will have to create a custom iframe renderer which would do the following:

- Render the iframe while injecting JavaScript code in the WebView to fire an event when the dom is loaded, see [`DOMContentLoaded`](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event);
- Render an image matching the iframe box boundaries on top of the iframe (absolutely positionned);
- When the `DOMContentLoaded` event fires, remove the masking image on top.

[Example on how to create a custom iframe renderer here](https://github.com/native-html/plugins/tree/master/packages/iframe-plugin#customizing-the-renderer).
