### ISSUE TITLE
Warning references outdated "ignoredTags"

### ISSUE THREAD

**Issue by Slapbox** [meliorence/react-native-render-html#541]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

`The "label" tag is a valid HTML element but is not handled by this library. You must extend the default HTMLElementModel for this tag with "customHTMLElementModels" prop and make sure its co
ntent model is not set to "none". If you don't want this tag to be rendered, add it to "ignoredTags" prop array.`

But from what I can tell this prop has been migrated to `ignoredDomTags` -- https://meliorence.github.io/react-native-render-html/docs/migration-guide#renamed-and-moved-props

### React Native Information

```sh
0.64.3
```

### RNRH Version

6.3.0

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

N/A

**Comment by jsamr** [comment]
@Slapbox thanks!
