### ISSUE TITLE
using inline css is okay but when specify class for element then it's not work as i expected

### ISSUE THREAD

**Issue by isekaimaou1109** [meliorence/react-native-render-html#542]
```javascript
import { useWindowDimensions } from 'react-native';
import RenderHtml from 'react-native-render-html';

export default function App() {
  const source = {
    html: `
      <html>
        <head>
          <title>Title</title>
          <style>
            .demo {
              color: red;
              text-align: center;
            }
          </style>
        </head>

        <body>
          <p class='demo'>
            Hello World!
          </p>
        </body>
      </html>
    `
  };

  const { width } = useWindowDimensions();
  return (
    <RenderHtml
      contentWidth={width}
      source={source}
    />
  );
}
```

Above is sample code but i change from inline css to style tag html but it's not work as well. So thanks in advanced for your reply.

this image is i used style tag html in head html 
![image](https://user-images.githubusercontent.com/49366277/147824044-09a383d1-9a05-4634-952d-41d0151d90cd.png)

And this image is i used inline css 
![image](https://user-images.githubusercontent.com/49366277/147824113-259441bc-a30d-410c-bd78-ba522f42e6ff.png)

**Comment by jsamr** [comment]
The `<style>` tag is not yet supported. See also https://github.com/meliorence/react-native-render-html/issues/437#issuecomment-876426813
You are welcome to open a feature request in our canny. https://native-html.canny.io/features
