### ISSUE TITLE
why in iOS can't selectable text just only copy

### ISSUE THREAD

**Issue by apabuatapa** [meliorence/react-native-render-html#544]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

 I want make html text but when I active selectable on iOS cannot selectable only copy, 
 
 please shifuu!!! help me.. how I can

### React Native Information

```sh
the result just run copy only
```

### RNRH Version

"react-native-render-html": "^6.1.0",

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

can't selectable only copy on iOS

**Comment by jsamr** [comment]
Hi @apabuatapa, and thank you for your report! Unfortunately, some important information is missing from your ticket and thus this is not actionable for us. Feel free to resubmit a ticket with all required information, thank you!
