### ISSUE TITLE
Link on Android not work

### ISSUE THREAD

**Issue by dkjeune** [meliorence/react-native-render-html#546]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

When I click on a link on IOS, it open the browser.
On Android, nothing happen.
Any help ?

### React Native Information

```sh
No browser open on android
```

### RNRH Version

last version

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

nope

**Comment by jsamr** [comment]
Thank you @dkjeune for taking time to fill this report. Unfortunately, the report doesn't provide the least minimal reproduction, not even the HTML that would produce the issue you are reporting. I am going to close the issue now as this is not actionable for us, but if a viable reproduction is to be provided, I will reopen.

**Comment by eithe** [comment]
Not that it helps, but I'm getting reports of the same (perhaps only some Android devices?), and I was finally able to reproduce it on a Pixel 2 API 30 emulator running Android 11.

I didn't have time to debug this further, but I have a common component that renders html in the app (that uses react-native-render-html) so what I did as a workaround was just to handle onPress manually like so:

```
<HTML
  ...
  renderersProps={{
    a: {
      onPress: (_, href) => {
        Linking.openURL(href);
      },
    },
  }}
  source={{ html }}
/>
```

**Comment by jsamr** [comment]
@eithe Would you mind providing the HTML code, React Native version and RNRH version that triggered this undesired behavior? I tried with the same emulator configuration as you did, and the link press worked (React Native 0.64). My code snippet looked like this:

```html
<a href="https://google.com/">This is a test</a>
```

**Comment by eithe** [comment]
Good point, @jsamr. I must admit I was running RNRH 6.1.0, but I upgraded to 6.3.3 now. RN 0.65.1.

This does not work:
![test](https://user-images.githubusercontent.com/204129/150785725-6a6a1786-a6d3-4f2f-ac25-7fef70a1588b.png)
This does:
![test2](https://user-images.githubusercontent.com/204129/150786062-6c31769d-74af-4ee2-88c9-727c563b620b.png)

I get that this is quite hard for you to debug, it should be our responsibility to create a minimal working example where it fails instead of you having to dig.

**Comment by jsamr** [comment]
Thanks @eithe for providing this additional information. I managed to reproduce the issue by upgrading from RN 0.64 to RN 0.67 on my "sandbox" project that I use for testing! Now I can investigate...

**Comment by jsamr** [comment]
I found the issue. Check the implementation of the default onAPress:

https://github.com/meliorence/react-native-render-html/blob/073d4db2f2ddab63bdd036045f68e1cd781a8d2d/packages/render-html/src/context/defaultRendererProps.ts#L4-L8

For a reason yet to determine, `await Linking.canOpenURL(href)` ceased returning `true` for HTTP(S) URIs on Android. This is obviously a bug on React Native side, but I will have to take it into account and provide a fix.

**Comment by eithe** [comment]
Nice find, @jsamr! Thanks for investigating and thanks again for your efforts on this project, greatly appreciated.

**Comment by jsamr** [comment]
I've opened a ticket on React Native issue tracker https://github.com/facebook/react-native/issues/32960

**Comment by jsamr** [comment]
Fix has been released https://github.com/meliorence/react-native-render-html/releases/tag/v6.3.4

**Comment by jsamr** [comment]
@eithe Thanks for the sponsor and kind feedback, it always lifts one's spirit!

**Comment by iphonic** [comment]
How do you access `this.state` inside onPress?

```
const renderersProps = {
    a: {
      onPress(event, url, htmlAttribs, target) {
        if (url.includes('tc')) {
            this.setState({showTerms:true,showPrivacy:false})
        }else if (url.includes('pv')) {
            this.setState({showTerms:false,showPrivacy:true})
        }
      }
    }
  }
```
