### ISSUE TITLE
can't selectable highlight in IOS 

### ISSUE THREAD

**Issue by apabuatapa** [meliorence/react-native-render-html#550]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

![Screen Shot 2022-02-03 at 12 54 14](https://user-images.githubusercontent.com/75601681/152289196-16f2d3b4-15aa-4e77-947e-72523a673711.png)

i want to make my description page using html and can be copied, but when i use this library and i use it on ios selectable can only copy can't select , how to solve it?

### React Native Information

```sh
react-native: ^0.64.3
```

### RNRH Version

"react-native-render-html": "^6.1.0",

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://github.com/meliorence
/
[react-native-render-html](https://github.com/meliorence/react-native-render-html)

**Comment by apabuatapa** [comment]
what missing reproduction ?? I don't know??

**Comment by jsamr** [comment]
Dear @apabuatapa, we have a process to handle bug reports, in which reports with missing critical information can be closed without notice. I suggest you read our contribution guide to get familiar with what we mean by "reproduction", see https://github.com/meliorence/react-native-render-html/blob/master/CONTRIBUTING.adoc

I will be very happy to  reopen, help and investigate when the required information is provided in the body of the ticket. Thank you for your understanding!

**Comment by CDBridger** [comment]
Here is a reproducible example https://snack.expo.dev/0_Ifj62U- 

Run this snack on iOS and try and highlight only a subset of the text and you'll find you cant. There have been multiple issues raised on this but no updates recently (in the past year). Is this bug fixable or is dependent on some existing bug in react native?

**Comment by jsamr** [comment]
This is a known bug in React Native, involving nested `Text` components. Reproduction here: https://snack.expo.dev/@jsamr/text-fails-to-be-selectable-on-ios
Feel free to report to react native team: https://github.com/facebook/react-native/issues/new/choose
