### ISSUE TITLE
Android TypeError Cannot read property 'html' of undefined

### ISSUE THREAD

**Issue by putuoka** [meliorence/react-native-render-html#553]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Can't produce the bugs because randomly appear on different android real device. This error log captured from sentry causing force close to the Apps in user side. This error message from device android Redmi K20 Pro. Other android device seem working fine. 

### React Native Information

```sh
"react-native": "0.63.4",
```

### RNRH Version

"react-native-render-html": "^6.3.1",

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

Here the code part:

< KeyboardAvoidingView >
...

`<View style={[apply('flex mb-5')]}>

                                    <View style={apply('mt-1')}>
                                        <HTML
                                            source={{`<View style={[apply('flex mb-5')]}>

                                    <View style={apply('mt-1')}>
                                        <HTML
                                            source={{
                                                html:
                                                    props.loginContent?.data?.middle_content.html ??
                                                    '<div></div>',
                                            }}
                                            containerStyle={apply('flex')}
                                            renderersProps={renderersProps}
                                            systemFonts={systemFonts}
                                            contentWidth={width}
                                            tagsStyles={tagsStyles}
                                        />
                                    </View>
                                    <Text
                                        onPress={() =>
                                            props.navigation.navigate('WebView', {
                                                link: props.loginContent?.data?.footer_content.url,
                                            })
                                        }
                                        style={[styles.text, apply('text-orange underline mt-6')]}>
                                        {props.loginContent?.data?.footer_content.title}
                                    </Text>
                                </View>`
                                                html:
                                                    props.loginContent?.data?.middle_content.html ??
                                                    '<div></div>',
                                            }}
                                            containerStyle={apply('flex')}
                                            renderersProps={renderersProps}
                                            systemFonts={systemFonts}
                                            contentWidth={width}
                                            tagsStyles={tagsStyles}
                                        />
                                    </View>
                                    <Text
                                        onPress={() =>
                                            props.navigation.navigate('WebView', {
                                                link: props.loginContent?.data?.footer_content.url,
                                            })
                                        }
                                        style={[styles.text, apply('text-orange underline mt-6')]}>
                                        {props.loginContent?.data?.footer_content.title}
                                    </Text>
                                </View>`
...

< /KeyboardAvoidingView>

**Comment by jsamr** [comment]
Hi @putuoka and thank you for your contribution! Your code snippet is unfortunately not in a reproducible state, and my availability to investigate issues this month is very limited. To help me help you, would you mind sharing an expo snack which reproduces the issue you encountered? That would vastly enhance the odds this issue is tackled soon.
