### ISSUE TITLE
 elementModel.isTranslatableTextual is not a function.

### ISSUE THREAD

**Issue by hanhtv204** [meliorence/react-native-render-html#556]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

In my html, I have use iframe. I got this warning and my iframe was not displayed.
`The "iframe" tag is a valid HTML element but is not handled by this library. You must extend the default HTMLElementModel for this tag with "customHTMLElementModels" prop and make sure its content model is not set to "none". If you don't want this tag to be rendered, add it to "ignoredDomTags" prop array. `

As warning above, I added prop like this and got error 
>  elementModel.isTranslatableTextual is not a function.
```
customHTMLElementModels={{
  iframe: {
      tagName: 'iframe',
      contentModel: HTMLContentModel.block,
  },
}}
```

Is there anyone met this issue? 
Thank you

### React Native Information

```sh
"react": "17.0.2",
"react-native": "0.66.4",
```

### RNRH Version

"react-native-render-html": "^6.3.4",

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

Above information

**Comment by jsamr** [comment]
@hanhtv204 Are you using Typescript or JavaScript? If you are using TS, isn't this code snippet causing a type error?
To render iframes, use this plugin: https://github.com/native-html/plugins/tree/master/packages/iframe-plugin#readme

**Comment by hanhtv204** [comment]
> @hanhtv204 Are you using Typescript or JavaScript? If you are using TS, isn't this code snippet causing a type error? To render iframes, use this plugin: https://github.com/native-html/plugins/tree/master/packages/iframe-plugin#readme

I use Javascript @jsamr

**Comment by jsamr** [comment]
@hanhtv204 All right; to use `customHTMLElementModels`, you should take inspiration from this guide: https://meliorence.github.io/react-native-render-html/docs/guides/custom-renderers#example-registering-a-new-tag
I am going to close now; if you need to render iframes, just use the plugin I mentioned.
