### ISSUE TITLE
[DOUBT] tag <a> can get a Callback?

### ISSUE THREAD

**Issue by Girum** [meliorence/react-native-render-html#560]
Hi! I tested to send a <a>tag with a link. With renders ok and open the browser when I click that. But, I when I used a DeepLink to open, even if it's ok, I need to fire another functions in the code (in the same time i click the link). There's any way to do that? To when I click the hyperlink, call another functions?

**Comment by jsamr** [comment]
@Girum Yes! See https://meliorence.github.io/react-native-render-html/docs/faq#how-to-intercept-press-events-on-links

**Comment by Girum** [comment]
> @Girum Yes! See https://meliorence.github.io/react-native-render-html/docs/faq#how-to-intercept-press-events-on-links

Thanks! Helped a lot!
