### ISSUE TITLE
textDecorationColor and textDecorationLine on a tags does not take effect

### ISSUE THREAD

**Issue by Bruce-Ming** [meliorence/react-native-render-html#564]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

```
  <RenderHtml
                baseStyle={{
                  lineHeight: 27,
                  fontSize: 17,
                  color: '#000000b3',
                  paddingHorizontal: 0,
                  paddingVertical: 0
                  // textDecorationColor: '#1890ff'
                }}
                tagsStyles={{
                  p: { lineHeight: 27, fontSize: 17, marginVertical: 0, color: '#000000b3' },
                  img: { objectFit: 'contain', textAlign: 'center' },
                  ol: { color: '#1890ff', paddingLeft: 10, marginVertical: 0 },
                  ul: {
                    color: '#1890ff',
                    paddingLeft: 10,
                    marginVertical: 0
                  },
                  /*   section: {
                display: 'flex',
                // width: WIDTH - 40,
                flexDirection: 'cloumn',
                // alignItems: 'flex-start',
                marginLeft: 0,
                paddingLeft: 0
              }, */
                  li: {
                    lineHeight: 27,
                    fontSize: 17,
                    paddingLeft: 10,
                    color: '#000000b3'
                  },
                  strong: {
                    lineHeight: 27,
                    textAlign: 'left'
                  },

                  h1: { fontSize: 20, lineHeight: 27, color: '#000000', marginVertical: 0 },
                  h6: { fontSize: 14, lineHeight: 20, marginVertical: 0 },
                  hr: {
                    height: 1,
                    backgroundColor: '#e7e7e7',
                    marginVertical: 0
                  },

                  a: {
                    textDecorationLine: 'underline',
                    color: '#1890ff',
                    fontSize: 22,
                    textDecorationColor: 'red'
                  },
    
                  h4: {
                    fontSize: 16,
                    color: '#000000b3',
                    marginVertical: 0
                  }
                }}
                classesStyles={{ h1: { fontSize: 20, lineHeight: 27, color: '#000', marginVertical: 0 } }}
                contentWidth={WIDTH - 30}
                source={{ html: state?.content }}
                renderers={renderers}
                renderersProps={renderersProps}
                enableExperimentalMarginCollapsing={true}
              />
```
this is my code ,i set  textDecorationColor and textDecorationLine on a tags,but it not take effect, textDecorationColor and textDecorationLine both all not take effect

### React Native Information

```sh
"react": "16.13.1",
    "react-native": "0.63.4",
```

### RNRH Version

 "react-native-render-html": "^6.3.4",

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/bJA77PiCI

On the above example, the textDecorationLine: none is valid, but the textDecorationColor: red is invalid. But in the react native version I use, both of them are not effective

### Additional Notes

But in the react native version  that I use, both of them are not effective, neither in ios nor in Android

**Comment by jsamr** [comment]
@Bruce-Ming It does work as expected on iOS in the reproduction you provided (I just changed the colors to make it more salient):
![image](https://user-images.githubusercontent.com/3646758/169015134-dfd8a8b9-1a26-4622-ae1a-d1ffa8a487be.png)

Also note that `textDecorationColor` is an iOS-only prop, see https://reactnative.dev/docs/text-style-props#textdecorationcolor-ios

**Comment by jsamr** [comment]
So, I don't think this is a bug, and I'm going to close the issue. But if you provide additional information on how you asserted that this is a bug, I'll eventually reopen.

**Comment by Slapbox** [comment]
> Also note that textDecorationColor is an iOS-only prop, see https://reactnative.dev/docs/text-style-props#textdecorationcolor-ios

Thanks for pointing this out!
