### ISSUE TITLE
The "colgroup" tag is a valid HTML element but is not handled by this library.

### ISSUE THREAD

**Issue by shivanitp** [meliorence/react-native-render-html#566]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

The "colgroup" tag is a valid HTML element but is not handled by this library.You must extend the default HTMLElementModel for this tag with "customHTMLElementModels" prop and make sure its content model is not set to "none". If you don\'t want this tag to be rendered, add it to "ignoredDomTags" prop array.

I'm facing this issue the tag name colgroup is not supported or handled by the  element and it's looks bed if the tag used in the data 
I used this ignoredDomTags but till it's displayed the same waring and error 

can you please help me with this

### React Native Information

```sh
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 6.52 GB / 15.84 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
 SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: 0.67.4 => 0.67.4
```

### RNRH Version

 "react-native-render-html": "^6.3.4",

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

 https://snack.expo.dev/@jsamr/rnrhtml-template

**Comment by jsamr** [comment]
@shivanitp Thanks for taking your time to fill this! Unfortunately, the "reproduction" you provided doesn't relate to the reported issue. Bug reports which don't include reproductions have a significantly lower chance of being addressed, and might be closed without author notice.

**Comment by Nulll-cyber** [comment]
i have same issue how .
