### ISSUE TITLE
does "contentWidth" not working when set contentWidth = width* 0.6

### ISSUE THREAD

**Issue by fukemy** [meliorence/react-native-render-html#569]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

I have set contentWidth = width*0.6 to ensure the width of html, but not working

### React Native Information

```sh
OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 181.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.3.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.06.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/thehe/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.0 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### RNRH Version

6.3.4

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

```

export function ChatHtml(props) {
    const { theme } = useContext(ThemeContext)
    const { width } = useWindowDimensions();
    const position = props.position ?? 'left'
    console.log('width' , width,  props.width)
    return (
        <View
            style={{
                ...style[position].container,
                backgroundColor: position === 'left' ? theme.leftChatBubbleBg : theme.rightChatBubbleBg
            }}>
            <RenderHtml
                contentWidth={width*0.6}
                source={{html: props.currentMessage.html}}
            />
        </View>
    )
}
```

### Additional Notes

![Screen Shot 2022-06-10 at 15 28 15](https://user-images.githubusercontent.com/8202437/173024588-208be9e7-734c-4ac1-9d02-28625745299f.png)

Here is image

**Comment by fukemy** [comment]
im. sorry, it's my fault, i need to set parent container width

**Comment by kkkasio** [comment]
> im. sorry, it's my fault, i need to set parent container width

can you show a solution? just add a width on the parent element?

**Comment by fukemy** [comment]
I just set maxWidth to parentview
