### ISSUE TITLE
testID override issue

### ISSUE THREAD

**Issue by DaliaElhefny** [meliorence/react-native-render-html#572]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-render-html@6.3.4` for the project I'm working on.

I need the HTML rendered to have testID so that it can b used in automation testing
My problem was that when I pass testID through defaultTextProps prop, it gets overridden with the tagName

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-render-html/src/helpers/getNativePropsForTNode.ts b/node_modules/react-native-render-html/src/helpers/getNativePropsForTNode.ts
index 113b28c..415eb92 100644
--- a/node_modules/react-native-render-html/src/helpers/getNativePropsForTNode.ts
+++ b/node_modules/react-native-render-html/src/helpers/getNativePropsForTNode.ts
@@ -70,7 +70,7 @@ export default function getNativePropsForTNode<
     children,
     onPress: syntheticOnPress,
     style: [style, passedNativeProps?.style, switchProp.style],
-    testID: tnode.tagName || undefined
+    testID: switchProp.testID ||tnode.tagName || undefined
   };
   return nativeProps as any;
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jsamr** [comment]
@DaliaElhefny Appreciate the proposition! Are you willing to offer a PR? I'd approve it quickly.

**Comment by jsamr** [comment]
@DaliaElhefny You don't need to, just fork this repository, create a branch with the fix, and then [visit the PR page on Github](https://github.com/meliorence/react-native-render-html/pulls), you should be able to create a PR out of your forked repository branch.

**Comment by DaliaElhefny** [comment]
@jsamr here is the PR https://github.com/meliorence/react-native-render-html/pull/574

**Comment by DaliaElhefny** [comment]
@jsamr when will be the next release?
