### ISSUE TITLE
Italic and bold fonts not working for their corresponding tags on android

### ISSUE THREAD

**Issue by Lastofthefirst** [meliorence/react-native-render-html#581]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

On android, bold and italic tagfonts, and maybe others, are not rendering the custom loaded fonts.

### React Native Information

```sh
System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 20210102.202219.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.2
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.60.0
    Expo Workflow: managed
```

### RNRH Version

    "react-native-render-html": "^6.3.4",

### Tested Platforms

- [X] Android
- [X] iOS
- [X] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/@lastof/react-native-html-render-and-bold-italic-fonts

**Comment by jsamr** [comment]
The good way to handle fonts [is laid out in the FAQ](https://meliorence.github.io/react-native-render-html/docs/faq#custom-font-families-dont-work-whats-happening), and requires defining XML fonts so that all variants of the same typeface are registered under the same font identifier (e.g.: "Inter" instead of "Inter_Bold", "Inter_Normal" ...etc). 

Unfortunately, [Expo doesn't allow this](https://docs.expo.dev/guides/using-custom-fonts/) as of today. This is a limitation of Expo, not a bug.

**Comment by tremby** [comment]
@jsamr:
> Unfortunately, [Expo doesn't allow this](https://docs.expo.dev/guides/using-custom-fonts/) as of today. This is a limitation of Expo, not a bug.

That link is now dead. Do you know if this is still a limitation?

**Comment by jsamr** [comment]
https://docs.expo.dev/develop/user-interface/fonts/

**Comment by tremby** [comment]
If I'm understanding everything right, that's a yes.
