### ISSUE TITLE
Hi @jsamr , I am facing this issue please help...!! First html content is good if I used this library ->  react-native-htmlview

### ISSUE THREAD

**Issue by DeepakSharma04** [meliorence/react-native-render-html#585]
Hi @jsamr , I am facing this issue in IOS APP please help...!! First html content is good if I used this library ->  react-native-htmlview

                               <HTMLView
                                value={item.body.replace(/\n/g, '')}
                                gesMaxWidth={Dimensions.get('window').width}
                              />

But if I used this -> react-native-render-html , Second html content shows vertical space .

                      <ScrollView horizontal={true}>
                                <SafeAreaView>
                                  <RenderHtml
                                    contentWidth={width}
                                    source={{ html: item.body }}
                                    enableExperimentalMarginCollapsing={true}
                                    enableExperimentalBRCollapsing={true}
                                    enableExperimentalGhostLinesPrevention={true} />
                                </SafeAreaView>
                              </ScrollView>

![Simulator Screen Shot - iPhone 11 - 2022-09-16 at 12 07 20](https://user-images.githubusercontent.com/96714958/190573412-476d6f7a-a068-4b60-817e-8d433bfc1c9d.png)

_Originally posted by @DeepakSharma04 in https://github.com/meliorence/react-native-render-html/issues/516#issuecomment-1248978401_

**Comment by jsamr** [comment]
To be able to reproduce, I would need the HTML code you are trying to render.

**Comment by DeepakSharma04** [comment]
const item.body = `
<div>asd</div>
<div><br></div>
<div>asda</div>
<div>as</div>
<div><br></div>
<div>asda</div>
<div><br></div>
<div>asd</div>
<div><br></div>
`;

**Comment by DeepakSharma04** [comment]
`<div>asd</div>
<div><br></div>
<div>asda</div>
<div>as</div>
<div><br></div>
<div>asda</div>
<div><br></div>
<div>asd</div>
<div><br></div>`
