### ISSUE TITLE
App is crashing when heading tags are used

### ISSUE THREAD

**Issue by gs-alranjan** [meliorence/react-native-render-html#595]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

When using heading tags (Eg. h1,h2, etc), the layout crashes with the following error as in [Image](https://drive.google.com/file/d/1SSfAyh07XmfXSm_No_jZ3xyPK7Gt6thW/view?usp=share_link)

Other HTML tags (like p, a, etc) are working fine.

### React Native Information

```sh
App was run on ios, android simulator and real devices as well
```

### RNRH Version

"react-native-render-html": "^6.3.4"

"react": "16.13.1",
"react-native": "0.63.4",

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

```
import React from "react";
import { Dimensions } from "react-native";
import RenderHtml from "react-native-render-html";
import { SafeAreaView } from "react-native-safe-area-context";

const source = {
  html: `<h1> hello world </h1>`
};

export class HtmlComponent {
  public render() {
    return (
      <SafeAreaView>
        <RenderHtml source={source} contentWidth={ Dimensions.get("window").width}/>
      </SafeAreaView>
    );
  }
}
```

**Comment by jsamr** [comment]
Looks like a mismatch in domutils version; make sure the version range required by `@native-html/transient-render-tree` (^2.8.0) matches the resolved version in your project.

**Comment by gs-alranjan** [comment]
> Looks like a mismatch in domutils version; make sure the version range required by `@native-html/transient-render-tree` (^2.8.0) matches the resolved version in your project.

Since `@native-html/transient-render-tree` is deprecated , "@native-html/transient-render-engine" "11.2.3" is auto-resolved.

**Comment by jsamr** [comment]
@gs-alranjan You're correct, I meant `@native-html/transient-render-engine`.

**Comment by gs-alranjan** [comment]
@jsamr still, headings are causing issues to be rendered. Any alternate solution?

**Comment by jsamr** [comment]
@gs-alranjan 

> Looks like a mismatch in domutils version; make sure the version range required by @native-html/transient-render-engine (^2.8.0) matches the resolved version in your project.

This still holds true. Depending on your package manager, you can see which version(s) of a peculiar package are installed. `yarn why domutils` or `npm why domutils`. Happy to reopen if this really turns out to be a bug, but currently it does seem like a packager issue.
