### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by dvijeniii05** [meliorence/react-native-render-html#600]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Simply cannot install the package. 

Using `yarn add react-native-render-html` results in:
```
yarn add react-native-render-html    
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-render-html: connect ENETUNREACH 2606:4700::6810:1523:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/adil/CyberFantasy/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Using `npm install react-native-render-html` just getting stuck on:
```
npm install react-native-render-html
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠙ idealTree:CyberFantasy: sill idealTree buildDeps
```

I tried to remove node-modules package and package-lock.json

Nothing helps. Would appreciate any help.

### React Native Information

```sh
"react-native": "0.69.5",
```

### RNRH Version

Latest, just trying to install

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

npm install react-native-render-html
yarn add react-native-render-html

**Comment by jsamr** [comment]
@dvijeniii05 This is a networking issue between your machine and npm repositories, there is nothing actionable for us here, unless proven otherwise. Closing, but please reopen if you find more information that would point to something we can do on our end.
