### ISSUE TITLE
How to show images selected from devices like android and iOS?

### ISSUE THREAD

**Issue by Shivani12345** [meliorence/react-native-render-html#601]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

can we show local  images choose or selected from android/iOS device like i choose image from iOS device and rerender to HTML

`<td><img src='Users/name/Library/Developer/CoreSimulator/Devices/32123-CRTI-475D-919E-8BF5549BE600/data/Containers/Data/Application/F2DEDC7B-152F-43CF-8911-8CFA1C8E0A9C/tmp/react-native-image-crop-picker/87BGNI32-D762-4CF6-A180-32423423FCAF.jpg' alt="" border=3 height=100 width=80></img></th>`
 
 But it showing error like
 

>  No suitable image URL loader found for about:///URL

I have tried #588  but its not working.

### React Native Information

```sh
expo
```

### RNRH Version

 `"react-native-render-html": "^6.3.4"`

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

Not available yet

**Comment by jsamr** [comment]
> No suitable image URL loader found for about:///URL

This error message gives a hint: you might have to provide a URL schema (`file://`) in this case. But no guarantees this will work; and RNRH doesn't claim support for local images rendering.
