### ISSUE TITLE
App crashes when scrolled to bottom of the screen.

### ISSUE THREAD

**Issue by pravin512** [meliorence/react-native-render-html#605]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

 When scroll to the end, app crashes.
HTML :

```html
<p>This is reading content from user</p>
```

### React Native Information

```sh
running on emulator.
```

### RNRH Version

"react": "17.0.2",
 "react-native": "0.68.1",
"react-native-render-html": "6.3.4",

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

<RenderHTML style={{color:'#000'}} source={{html:'<p>This is reading content from user</p>'}} />

**Comment by pravin512** [comment]
this is **not react-native-render-html issue**, issue is caused by webview used in the screen.
<WebView
        style={{height:400}}
        androidLayerType="hardware" //or software
        ref={webviewRef}
        scalesPageToFit={false}
        mixedContentMode="compatibility"
        onMessage={onMessage}
        javaScriptEnabledAndroid={true}
        javaScriptEnabled={true}
        useWebKit={true} 
        allowsInlineMediaPlayback={true}
        allowsFullscreenVideo={true}

**Comment by jsamr** [comment]
Note that you can set `androidLayerType` with `defaultWebViewProps` https://meliorence.github.io/react-native-render-html/api/renderhtmlprops#defaultwebviewprops
