### ISSUE TITLE
img with border-radius not working

### ISSUE THREAD

**Issue by ChauVV** [meliorence/react-native-render-html#607]
### Description

I try to render img tag with border-radius but the img not work.
my html is: 
`<img style="border-radius: 12px;" src="...">`

if i use `renderers` to render img
the img will not show because <Image .../> do'nt have width, height.

i add borderRadius in alterChildren still not work
`
alterChildren={node => {
          if (node.name === 'img') {
            node.attribs['border-radius']= '12px';
          }
          return node.children;
        }}
`

### RNRH Version

5.1.1

It's still not work on latest version: 6.3.4
`
    <RenderHtml
...
 domVisitors={domVisitors}
 />
 
   const domVisitors = {
    onElement,
  };
  
  function onElement(element) {
    if (element.tagName === 'img') {
      element.attribs['border-radius'] = '12px';
    }
  }
`

**Comment by nctung** [comment]
Hi @ChauVV, I have same issues. How to fixed this?
