### ISSUE TITLE
Image can't render SVG from URL

### ISSUE THREAD

**Issue by stesvis** [meliorence/react-native-render-html#617]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

The library doesn't seem to be able to render SVG images from url, such as:
```html
<img alt="emoji" 
     src="https://cdnjs.cloudflare.com/ajax/libs/emojione/2.0.1/assets/svg/1f600.svg" 
     height="100" width="100" />
```

### React Native Information

```sh
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^47.0.13 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    Expo Workflow: managed
```

### RNRH Version

`^6.3.4`

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/@stesvis/image-with-inline-styles

### Additional Notes

In a regular HTML page the image shows correctly.

**Comment by yellowowl-hk** [comment]
facing this issue, is there any alternative to render the svg ?

**Comment by arasrezaei** [comment]
replace Image component with expo-image, and it works!

**Comment by stesvis** [comment]
> replace Image component with expo-image, and it works!

I don't think you fully understood the issue, you can't have expo elements in HTML.
The problem here is when the HTML contains an `<img ...` tag with SVG as source.

**Comment by arasrezaei** [comment]
> > replace Image component with expo-image, and it works!
> 
> I don't think you fully understood the issue, you can't have expo elements in HTML. The problem here is when the HTML contains an `<img ...` tag with SVG as source.

If your problem is that you want render svg from src, then the new `expo-image` support that
See:
https://docs.expo.dev/versions/unversioned/sdk/image/#supported-image-formats

And simply you can use **custom renderer** for <img /> tag.
See:
https://meliorence.github.io/react-native-render-html/docs/guides/custom-renderers

**Comment by arasrezaei** [comment]
import React from 'react';
import RenderHtml from 'react-native-render-html';
import { useWindowDimensions, Alert } from 'react-native';
import {Image} from 'expo-image':

function ImageRenderer({
  TDefaultRenderer,
  ...props
}) {
  return (
    <Image
      {...props}
    />
  );
}

const source = {
  html: `
<img alt="emoji" 
src="https://cdnjs.cloudflare.com/ajax/libs/emojione/2.0.1/assets/svg/1f600.svg" 
     height="100" width="100" />
`
};

const renderers = {
  img: ImageRenderer
};

export default function App() {
  const { width } = useWindowDimensions();
  return (
    <RenderHtml
      contentWidth={width}
      source={source}
      renderers={renderers}
    />
  );
}
