### ISSUE TITLE
use a custom component for rendering

### ISSUE THREAD

**Issue by dominicsavb** [meliorence/react-native-render-html#639]
I just migrate from v4...

how to use Custom Text Component, not using Text Component from react-native... for rendering text at tag p, b, etc...

Thank you

**Comment by jj-apps** [comment]
Same question.

**Comment by jsamr** [comment]
We don't use GitHub issue tracker for feature requests. Our feature request board is here: https://native-html.canny.io/features

**Comment by GaeCuure** [comment]
> We don't use GitHub issue tracker for feature requests. Our feature request board is here: https://native-html.canny.io/features

@jsamr so it is not possible at the moment?

**Comment by jsamr** [comment]
@GaeCuure correct; PRs welcome though!
