### ISSUE TITLE
tagsStyles not working with custom font

### ISSUE THREAD

**Issue by stesvis** [meliorence/react-native-render-html#640]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

In my app I am using a custom google font (Lato) but I am unable to apply it to `RenderHTML` using the `tagsStyles` property.
See the snack sample, the text inside the `<p>` tag should render in _italic_ font.

### React Native Information

```sh
confer snack
```

### RNRH Version

`"react-native-render-html": "^6.3.4"`

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/@stesvis/tagsstyles-bug

**Comment by ctriantaf** [comment]
Have you looked at the `systemFonts` prop as described in the documentation: https://meliorence.github.io/react-native-render-html/api/renderhtmlprops#systemfonts? I'm using custom fonts with this library in my project.

**Comment by jsamr** [comment]
@stesvis @ctriantaf is correct; you must declare which fonts are available in the system for these to be matched via `systemFonts` prop. Also see [this tutorial, which is the preferred approach to register system fonts](https://github.com/jsamr/react-native-font-demo#goal).

With `@expo-google-fonts`, you will not get proper font face definitions with modifiers support (italic, normal, bold), commonly referred to as ["style linking"](https://www.smashingmagazine.com/2013/02/setting-weights-and-styles-at-font-face-declaration/#style-linking) in the Web space. What will happen is ending up with [faux font rendering](https://fonts.google.com/knowledge/glossary/faux_fake_pseudo_synthesized). This is an unfortunate limitation of Expo.
