### ISSUE TITLE
`<img>` embeds possibly not making use of `srcset` attribute resulting in blurry images

### ISSUE THREAD

**Issue by mmkthecoolest** [meliorence/react-native-render-html#645]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

I am unsure if this is intended behavior, but based on #37, I expected that the `srcset` attribute would be used when rendering an image. However, the image I am trying to display ends up being blurry, when other HTML renderers display a higher resolution image. I tried ignoring the `height` and `width` styles and am still getting the same results. Please let me know if I am missing something or if this unusual behavior has already been reported elsewhere.

Screenshot:
![image](https://github.com/meliorence/react-native-render-html/assets/27556124/e5aad178-2deb-427f-bf44-fc285a5cca92)

HTML tag used: `<img decoding="async" fetchpriority="high" class="alignnone  wp-image-1936" src="https://zenbud.health/wp-content/uploads/2023/10/VNS-PTSD-2-1000-2017-10-300x167.jpg" alt="" width="640" height="356" srcset="https://zenbud.health/wp-content/uploads/2023/10/VNS-PTSD-2-1000-2017-10-300x167.jpg 300w, https://zenbud.health/wp-content/uploads/2023/10/VNS-PTSD-2-1000-2017-10-600x335.jpg 600w, https://zenbud.health/wp-content/uploads/2023/10/VNS-PTSD-2-1000-2017-10.jpg 1000w" sizes="(max-width: 640px) 100vw, 640px" />`

URL of source page: https://zenbud.health/9-stress-relief-exercises-you-can-do-in-your-everyday-life/

### React Native Information

```sh
confer snack
```

### RNRH Version

"react-native-render-html": "^6.3.4"

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/n8Aza8HlB

**Comment by jsamr** [comment]
@mmkthecoolest `srcset` is not supported yet. However, [you can implement a custom image renderer](https://meliorence.github.io/react-native-render-html/docs/content/images#custom-renderer) and add support for it. PRs also welcomed!

**Comment by mmkthecoolest** [comment]
How do I extract the attributes for the `img` tag using the custom renderer implementation? I am having a hard time figuring that out based on the linked documentation. I tried writing my own renderer based on the documentation to test how it works.

```javascript
const ImgRenderer = ({
    ...props
  }) => {
    const { Renderer, rendererProps } = useInternalRenderer('img', props);
    console.log(rendererProps);
    return (
      <Text>This is an image</Text>
    );
  };
```
The console logs can't seem to print the values of the `srcset` attribute.

**Comment by jsamr** [comment]
@mmkthecoolest `props.tnode.attributes` ([see renderer props](https://meliorence.github.io/react-native-render-html/docs/guides/custom-renderers#renderer-props-summary))
