### ISSUE TITLE
Not working android Realme device 

### ISSUE THREAD

**Issue by MUSHTHAK2899** [meliorence/react-native-render-html#649]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Not working android Realme device 

### React Native Information

```sh
<ScrollView
            showsHorizontalScrollIndicator={false}
            style={styles.ContentContainer}>
            {resTermsCondition.map(item => {
              const source = {
                html: `${item?.description}`,
              };
              return (
                <View style={styles.Text}>
                  <RenderHtml contentWidth={width} source={source} />
                </View>
              );
            })}
          </ScrollView>
```

### RNRH Version

 "react-native-render-html": "^6.3.4",

### Tested Platforms

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

aa

### Additional Notes

aa

**Comment by jsamr** [comment]
Closing as this report doesn't follow [our contribution guidelines](https://github.com/meliorence/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug).
