### ISSUE TITLE
React Native 0.74 (Bridgeless) Support

### ISSUE THREAD

**Issue by oktaysenkan** [meliorence/react-native-render-html#657]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Hello,

React Native is transitioning to bridgeless architecture with version 0.74. This architecture aims to improve performance and maintainability by removing the JavaScript bridge, which has traditionally been a bottleneck.

I am currently using your library `react-native-render-html` in my project. It's been incredibly useful, and I appreciate all the effort that goes into maintaining it. With the changes in React Native 0.74, it appears that the library may require updates to ensure full compatibility with the new architecture.

## Links

**[About the New Architecture](https://reactnative.dev/docs/next/the-new-architecture/landing-page)**
**[New Architecture working group](https://github.com/reactwg/react-native-new-architecture)**
**[Library support for New Architecture + Bridgeless in 2024](https://github.com/reactwg/react-native-new-architecture/discussions/167)**
**[Already migrated libs to take as an example](https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture#migration-status-of-popular-libraries)**

### React Native Information

```sh
-
```

### RNRH Version

-

### Tested Platforms

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

-

**Comment by jsamr** [comment]
@oktaysenkan Thank you for this report! AFAIK, the JS bridge only affects libraries with native modules (Java, Kotlin, Swift, C++ ...), so unless I'm missing something, this library wouldn't be affected. However, if you are aware of some incompatibility, feel free to point it out.
