### ISSUE TITLE
Sub and sup tags are not correctly aligned

### ISSUE THREAD

**Issue by todaywesleep** [meliorence/react-native-render-html#76]
How I can correct render and sub tags?
When I render sup task, text becoming common, and don't support textVerticalAlign: 'top', is always eat bottom. Any have issue?

**Comment by Exilz** [comment]
Hi, you can create a [custom renderer](https://github.com/archriss/react-native-render-html#creating-custom-renderers) and try to play with lineHeight and fontSize or something like that to render `<sup>` and `<sub>`.

Don't forget to use `passProps.key` to prevent warnings, and to [set your custom renderer as inline](https://github.com/archriss/react-native-render-html#making-your-custom-component-block-or-inline) (or it will cause a line break in your text).

If you're successful writing this, I'd gladly accept a pull request to bake in your renderers by default.

**Comment by brunoti** [comment]
The lineHeight solution doesn't work on Android. I tried anything, even absolutes and transforms, but the text just stayed the same.

Any news about this? I would love to help...

**Comment by saeedtkh** [comment]
Could you able to fix this problem? Any new?

**Comment by matteodanelli** [comment]
I'd like to support it too..

**Comment by jsamr** [comment]
Please vote the feature here: https://react-native.canny.io/feature-requests/p/support-superscript-and-subscript

**Comment by msfreit** [comment]
I need it too!! any updates?

**Comment by jsamr** [comment]
This feature, to be fully implemented, requires React Native to support `textAlignVertical: sub` and `textAlignVertical: sup`. As of React Native 0.63, those values are unsupported, and the `textAlignVertical` style rule [is only supported for Android](https://reactnative.dev/docs/0.62/text-style-props#textalignvertical). We do have a limited support for sub an sup, but only on Android. Although there is a bug as reported here #259, that will be fixed soon.

## [If you want to see this feature implemented, upvote the feature request here.]( https://react-native.canny.io/feature-requests/p/support-superscript-and-subscript)

**Comment by kshitijsharma6325** [comment]
wrapping` <sup>` `<sub>` tag within` <div>` did the work for me 
`<p>water is H<sub>2</sub>O</p>` --> `<p>water is H<div><sub>2</sub></div>O</p>`

**Comment by jsamr** [comment]
@kshitijsharma6325 I bet that would only work on Android, see https://github.com/meliorence/react-native-render-html/issues/76#issuecomment-660702309

**Comment by jsamr** [comment]
I am closing because this issue has to be fixed upstream.
