### ISSUE TITLE
number of lines Text Component

### ISSUE THREAD

**Issue by Juliocbr** [meliorence/react-native-render-html#94]
Is there a way to use the number of lines as the Text component?.

Thanks.

**Comment by Exilz** [comment]
Hi, unfortunately this is not supported at the moment.

This makes me think it could be a nice idea to add a prop that is spread to all (or only some ?) `<Text>` elements to add extra props. This could be useful for #85, rather than adding a specific `selectable` prop.

**Comment by Juliocbr** [comment]
@MSSPL-PiyaleeMaiti the only way I implemented something similar to the number of lines was

`text = text.substring(0, numberOfLines) + '...';`

You can do something similar to limit the number of characters using substring function, **numberOfLines** parameter represents the position where to end the extraction.

**Comment by Exilz** [comment]
By the way, if you just want to display like half the content, you can simply truncate the HTML string you're rendering before passing it to the module. It's way easier than having to alter the text nodes themselves.

It might be useful if you want to lock an article and display only half of it to unregistered users, for example.

If that's not what you're looking for, [alterData](https://github.com/archriss/react-native-render-html#alterdata) should let you do what you want.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@Exilz What is the status of numberOfLines for showing half html content? I need this features urgently. Or can you suggest any alternative solution so that I can show half html content using this package without using any substr() method. substr is not working for html content.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@Exilz I see your example but, I need also html tags when it's show, I want to show half content of a content with html tags. And here in your solution it's remove all html tag then show content without html tags. So what is the solution for my requirement. Can you suggest me?

**Comment by MSSPL-PiyaleeMaiti** [comment]
Is any solution found for this problem? I need this features urgently. Can anyone give me any solution?

**Comment by yasir-netlinks** [comment]
Hi, any updates regarding this! I have a paragraph `<p>...</p>` and Im trying to limit or shorten amount of characters to be shown.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@yasir-netlinks  You can use 'truncate-html', link is below, I solve my problem using this plugin.
https://www.npmjs.com/package/truncate-html

**Comment by idhindsight** [comment]
Any plans to fix this in the future?

**Comment by Asim13se** [comment]
Quick workaround is to wrap html view in a view and set maxHeight to 100 which equivalent to 4 line of text approximately:
```
<View style={{ maxHeight: 100 }}>
    <HTML html='some content' />
</View>
```

**Comment by oferRounds** [comment]
+

**Comment by oferRounds** [comment]
@Asim13se interesting, but I see a problem that `maxHeight` may cut off a work in the middle (while not adding ellipses). Have you experienced it?

**Comment by cmcaboy** [comment]
The maxHeight work around cuts it off on the middle, which is not ideal.

**Comment by cmcaboy** [comment]
I was able to fix this with [custom renderers](https://github.com/cmcaboy/react-native-render-html/tree/feature/numberOfLines#creating-custom-renderers):

```
<HTML
            html={`<p>${description}</p>`}
            tagsStyles={instructionsStyleDescription}
            renderers={{
              p: (_, children) => <Text numberOfLines={2}>{children}</Text>,
            }}
          />
```

**Comment by FFMerlin-aracom** [comment]
Unfortunately this doesn't work on all cases, especially for android. If your description contains some other html tags this will cause a crash on android, because you can't have nested views inside a <Text>.  On iOS this works just fine.

**Comment by jsamr** [comment]
This issue will be fixed in 6.x release, where you'll be able to use a special style property for that purpose.

**Comment by jsamr** [comment]
With the new foundry pre-release (see #434), you can define a custom renderer as such:

```jsx
const SpanRenderer = ({ TDefaultRenderer, textProps, ...props }) => {
    return <TDefaultRenderer {...props} textProps={{...textProps, numberOfLines: 2}} />
}

const renderers = {
    span: SpanRenderer
}
````

**Comment by jaideepYes** [comment]
@jsamr Hello Jules, `textProps ` are not working for me in a custom renderer. 
I am trying to work with following demo where `textProps={{...textProps, numberOfLines: 2}}` have no effect on `TDefaultRenderer `

```
import React from "react";
import RenderHTML from "react-native-render-html";

const source = {
  html: `
    <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus ac sapien sit amet imperdiet. Nunc cursus lacus mi, ut pellentesque elit elementum dignissim. Nulla faucibus lectus id justo sollicitudin scelerisque. Suspendisse iaculis quam a tortor consectetur facilisis. Proin quis nulla et ante rutrum aliquet quis in erat. Aliquam sapien ante, finibus ut tincidunt in, vehicula ac augue. Aliquam varius vulputate commodo. Sed et enim sed elit laoreet semper sed eget neque. Sed lobortis semper euismod. Maecenas a enim aliquet, aliquet lacus sed, ultricies lacus. Nulla tristique dui mi, ultricies pretium ante vestibulum laoreet. Nullam placerat facilisis vestibulum. Integer placerat tempor nisi, non efficitur magna elementum id.
    </p>
  `,
};

const defaultTextProps = {
  //numberOfLines: 2,
};

const ParagraphRenderer = ({ TDefaultRenderer, textProps, ...props }) => {
  return (
    <TDefaultRenderer
      {...props}
      textProps={{ ...textProps, numberOfLines: 2 }}
    />
  );
};

const renderers = {
  p: ParagraphRenderer,
};

function RenderHTMLTest(props) {
  return (
    <RenderHTML
      source={source}
      defaultTextProps={defaultTextProps}
      renderers={renderers}
    />
  );
}

export default RenderHTMLTest;
```
Although if i provide `numberOfLines` in  `defaultTextProps` it works. But it's useless in my case. I need to use it inside custom renderer only for  certain tag, not for whole html document.

I am testing it on  
```
"expo": "~40.0.0",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
"react-native-render-html": "^6.0.5",
```
I have tested it on both android and iphone. it doesn't work.

**Comment by jsamr** [comment]
@jaideepYes  It doesn't apply to TBlock renderers, which `p` renderer is. You might want to try
```jsx
const PRenderer = ({ TDefaultRenderer, textProps, ...props }) => {
  const tchildrenAreText = props.tnode.children.every(
    (t) => t.type === "text" || t.type === "phrasing"
  );
  const children = <TNodeChildrenRenderer tnode={props.tnode} />;
  return (
    <TDefaultRenderer {...props}>
      {tchildrenAreText ? <Text numberOfLines={2}>{children}</Text> : children}
    </TDefaultRenderer>
  );
};

const renderers = {
  p: PRenderer,
};
```

**Comment by jaideepYes** [comment]
@jsamr Thank you for your time to reply. Yes, above method works for me.
I am aware that above html snippet is converted to below Transient Render Tree.

```
<TBlock tagName="p">
  <TPhrasing anonymous>
    <TText anonymous data="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus ac sapien sit amet imperdiet. Nunc cursus lacus mi, ut pellentesque elit elementum dignissim. Nulla faucibus lectus id justo sollicitudin scelerisque. Suspendisse iaculis quam a tortor consectetur facilisis. Proin quis nulla et ante rutrum aliquet quis in erat. Aliquam sapien ante, finibus ut tincidunt in, vehicula ac augue. Aliquam varius vulputate commodo. Sed et enim sed elit laoreet semper sed eget neque. Sed lobortis semper euismod. Maecenas a enim aliquet, aliquet lacus sed, ultricies lacus. Nulla tristique dui mi, ultricies pretium ante vestibulum laoreet. Nullam placerat facilisis vestibulum. Integer placerat tempor nisi, non efficitur magna elementum id." />
  </TPhrasing>
</TBlock>
```
and i was supplying `textProps` to `TBlock` renderers. 
But i was expecting that library passes `textProps` down the hierarchy by itself to all its children of `type === "text"`.
similarly the way `defaultTextProps ` are applied to all text elements in `RenderHTML `.

I feel that library should provide a more flexible way to mix custom `textProps` with `defaultTextProps` in custom `renderers` and pass it down to all text children, rather than one hacking the whole flow of library of rendering TTree into VDOM for `text ` and `phrasing` elements, for such a trivial job of adding a one more property like `numberOfLines`. 

I am grateful for your great work. thank you.
